/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkUpsertGenesBody,
  CreateGeneBody,
  GeneBulkUpsertResponse,
  GeneResponse,
  HTTPValidationError,
  ListGenesApiV1GenesGetParams,
  PaginatedResponseGeneResponse,
  UpdateGeneBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Genes
 */
export const listGenesApiV1GenesGet = (
    params?: ListGenesApiV1GenesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseGeneResponse>(
      {url: `/api/v1/genes`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListGenesApiV1GenesGetQueryKey = (params?: ListGenesApiV1GenesGetParams,) => {
    return [
    `/api/v1/genes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListGenesApiV1GenesGetQueryOptions = <TData = Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError = HTTPValidationError>(params?: ListGenesApiV1GenesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGenesApiV1GenesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>> = ({ signal }) => listGenesApiV1GenesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGenesApiV1GenesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>>
export type ListGenesApiV1GenesGetQueryError = HTTPValidationError


export function useListGenesApiV1GenesGet<TData = Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListGenesApiV1GenesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGenesApiV1GenesGet>>,
          TError,
          Awaited<ReturnType<typeof listGenesApiV1GenesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGenesApiV1GenesGet<TData = Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError = HTTPValidationError>(
 params?: ListGenesApiV1GenesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGenesApiV1GenesGet>>,
          TError,
          Awaited<ReturnType<typeof listGenesApiV1GenesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGenesApiV1GenesGet<TData = Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError = HTTPValidationError>(
 params?: ListGenesApiV1GenesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Genes
 */

export function useListGenesApiV1GenesGet<TData = Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError = HTTPValidationError>(
 params?: ListGenesApiV1GenesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenesApiV1GenesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGenesApiV1GenesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Gene
 */
export const createGeneApiV1GenesPost = (
    createGeneBody: CreateGeneBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GeneResponse>(
      {url: `/api/v1/genes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGeneBody, signal
    },
      );
    }
  


export const getCreateGeneApiV1GenesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGeneApiV1GenesPost>>, TError,{data: CreateGeneBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createGeneApiV1GenesPost>>, TError,{data: CreateGeneBody}, TContext> => {

const mutationKey = ['createGeneApiV1GenesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGeneApiV1GenesPost>>, {data: CreateGeneBody}> = (props) => {
          const {data} = props ?? {};

          return  createGeneApiV1GenesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGeneApiV1GenesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createGeneApiV1GenesPost>>>
    export type CreateGeneApiV1GenesPostMutationBody = CreateGeneBody
    export type CreateGeneApiV1GenesPostMutationError = HTTPValidationError

    /**
 * @summary Create Gene
 */
export const useCreateGeneApiV1GenesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGeneApiV1GenesPost>>, TError,{data: CreateGeneBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGeneApiV1GenesPost>>,
        TError,
        {data: CreateGeneBody},
        TContext
      > => {

      const mutationOptions = getCreateGeneApiV1GenesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Gene
 */
export const getGeneApiV1GenesGeneIdGet = (
    geneId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GeneResponse>(
      {url: `/api/v1/genes/${geneId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetGeneApiV1GenesGeneIdGetQueryKey = (geneId?: string,) => {
    return [
    `/api/v1/genes/${geneId}`
    ] as const;
    }

    
export const getGetGeneApiV1GenesGeneIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError = HTTPValidationError>(geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGeneApiV1GenesGeneIdGetQueryKey(geneId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>> = ({ signal }) => getGeneApiV1GenesGeneIdGet(geneId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(geneId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGeneApiV1GenesGeneIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>>
export type GetGeneApiV1GenesGeneIdGetQueryError = HTTPValidationError


export function useGetGeneApiV1GenesGeneIdGet<TData = Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError = HTTPValidationError>(
 geneId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeneApiV1GenesGeneIdGet<TData = Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeneApiV1GenesGeneIdGet<TData = Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Gene
 */

export function useGetGeneApiV1GenesGeneIdGet<TData = Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneApiV1GenesGeneIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGeneApiV1GenesGeneIdGetQueryOptions(geneId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Gene
 */
export const updateGeneApiV1GenesGeneIdPatch = (
    geneId: string,
    updateGeneBody: UpdateGeneBody,
 ) => {
      
      
      return customInstance<GeneResponse>(
      {url: `/api/v1/genes/${geneId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateGeneBody
    },
      );
    }
  


export const getUpdateGeneApiV1GenesGeneIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>, TError,{geneId: string;data: UpdateGeneBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>, TError,{geneId: string;data: UpdateGeneBody}, TContext> => {

const mutationKey = ['updateGeneApiV1GenesGeneIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>, {geneId: string;data: UpdateGeneBody}> = (props) => {
          const {geneId,data} = props ?? {};

          return  updateGeneApiV1GenesGeneIdPatch(geneId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGeneApiV1GenesGeneIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>>
    export type UpdateGeneApiV1GenesGeneIdPatchMutationBody = UpdateGeneBody
    export type UpdateGeneApiV1GenesGeneIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Gene
 */
export const useUpdateGeneApiV1GenesGeneIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>, TError,{geneId: string;data: UpdateGeneBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGeneApiV1GenesGeneIdPatch>>,
        TError,
        {geneId: string;data: UpdateGeneBody},
        TContext
      > => {

      const mutationOptions = getUpdateGeneApiV1GenesGeneIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Bulk Upsert Genes
 */
export const bulkUpsertGenesApiV1GenesBulkPost = (
    bulkUpsertGenesBody: BulkUpsertGenesBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GeneBulkUpsertResponse>(
      {url: `/api/v1/genes/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkUpsertGenesBody, signal
    },
      );
    }
  


export const getBulkUpsertGenesApiV1GenesBulkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>, TError,{data: BulkUpsertGenesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>, TError,{data: BulkUpsertGenesBody}, TContext> => {

const mutationKey = ['bulkUpsertGenesApiV1GenesBulkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>, {data: BulkUpsertGenesBody}> = (props) => {
          const {data} = props ?? {};

          return  bulkUpsertGenesApiV1GenesBulkPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkUpsertGenesApiV1GenesBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>>
    export type BulkUpsertGenesApiV1GenesBulkPostMutationBody = BulkUpsertGenesBody
    export type BulkUpsertGenesApiV1GenesBulkPostMutationError = HTTPValidationError

    /**
 * @summary Bulk Upsert Genes
 */
export const useBulkUpsertGenesApiV1GenesBulkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>, TError,{data: BulkUpsertGenesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkUpsertGenesApiV1GenesBulkPost>>,
        TError,
        {data: BulkUpsertGenesBody},
        TContext
      > => {

      const mutationOptions = getBulkUpsertGenesApiV1GenesBulkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    