/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignTagBody,
  EntityTagResponse,
  HTTPValidationError,
  ListTagEntitiesApiV1TagsEntitiesGetParams,
  ListTagsApiV1TagsGetParams,
  MergeTagBody,
  RenameTagBody,
  SetEntityTagsBody,
  TagResponse,
  TaggedEntityResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Tags
 */
export const listTagsApiV1TagsGet = (
    params?: ListTagsApiV1TagsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TagResponse[]>(
      {url: `/api/v1/tags`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListTagsApiV1TagsGetQueryKey = (params?: ListTagsApiV1TagsGetParams,) => {
    return [
    `/api/v1/tags`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTagsApiV1TagsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = HTTPValidationError>(params?: ListTagsApiV1TagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsApiV1TagsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>> = ({ signal }) => listTagsApiV1TagsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTagsApiV1TagsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>>
export type ListTagsApiV1TagsGetQueryError = HTTPValidationError


export function useListTagsApiV1TagsGet<TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTagsApiV1TagsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTagsApiV1TagsGet>>,
          TError,
          Awaited<ReturnType<typeof listTagsApiV1TagsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTagsApiV1TagsGet<TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = HTTPValidationError>(
 params?: ListTagsApiV1TagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTagsApiV1TagsGet>>,
          TError,
          Awaited<ReturnType<typeof listTagsApiV1TagsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTagsApiV1TagsGet<TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = HTTPValidationError>(
 params?: ListTagsApiV1TagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tags
 */

export function useListTagsApiV1TagsGet<TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = HTTPValidationError>(
 params?: ListTagsApiV1TagsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTagsApiV1TagsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Rename Tag
 */
export const renameTagApiV1TagsTagIdPatch = (
    tagId: string,
    renameTagBody: RenameTagBody,
 ) => {
      
      
      return customInstance<TagResponse>(
      {url: `/api/v1/tags/${tagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: renameTagBody
    },
      );
    }
  


export const getRenameTagApiV1TagsTagIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>, TError,{tagId: string;data: RenameTagBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>, TError,{tagId: string;data: RenameTagBody}, TContext> => {

const mutationKey = ['renameTagApiV1TagsTagIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>, {tagId: string;data: RenameTagBody}> = (props) => {
          const {tagId,data} = props ?? {};

          return  renameTagApiV1TagsTagIdPatch(tagId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameTagApiV1TagsTagIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>>
    export type RenameTagApiV1TagsTagIdPatchMutationBody = RenameTagBody
    export type RenameTagApiV1TagsTagIdPatchMutationError = HTTPValidationError

    /**
 * @summary Rename Tag
 */
export const useRenameTagApiV1TagsTagIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>, TError,{tagId: string;data: RenameTagBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameTagApiV1TagsTagIdPatch>>,
        TError,
        {tagId: string;data: RenameTagBody},
        TContext
      > => {

      const mutationOptions = getRenameTagApiV1TagsTagIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Tag
 */
export const deleteTagApiV1TagsTagIdDelete = (
    tagId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/tags/${tagId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteTagApiV1TagsTagIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>, TError,{tagId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>, TError,{tagId: string}, TContext> => {

const mutationKey = ['deleteTagApiV1TagsTagIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>, {tagId: string}> = (props) => {
          const {tagId} = props ?? {};

          return  deleteTagApiV1TagsTagIdDelete(tagId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTagApiV1TagsTagIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>>
    
    export type DeleteTagApiV1TagsTagIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Tag
 */
export const useDeleteTagApiV1TagsTagIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>, TError,{tagId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTagApiV1TagsTagIdDelete>>,
        TError,
        {tagId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTagApiV1TagsTagIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Merge Tag
 */
export const mergeTagApiV1TagsTagIdMergePost = (
    tagId: string,
    mergeTagBody: MergeTagBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TagResponse>(
      {url: `/api/v1/tags/${tagId}/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeTagBody, signal
    },
      );
    }
  


export const getMergeTagApiV1TagsTagIdMergePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>, TError,{tagId: string;data: MergeTagBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>, TError,{tagId: string;data: MergeTagBody}, TContext> => {

const mutationKey = ['mergeTagApiV1TagsTagIdMergePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>, {tagId: string;data: MergeTagBody}> = (props) => {
          const {tagId,data} = props ?? {};

          return  mergeTagApiV1TagsTagIdMergePost(tagId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MergeTagApiV1TagsTagIdMergePostMutationResult = NonNullable<Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>>
    export type MergeTagApiV1TagsTagIdMergePostMutationBody = MergeTagBody
    export type MergeTagApiV1TagsTagIdMergePostMutationError = HTTPValidationError

    /**
 * @summary Merge Tag
 */
export const useMergeTagApiV1TagsTagIdMergePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>, TError,{tagId: string;data: MergeTagBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mergeTagApiV1TagsTagIdMergePost>>,
        TError,
        {tagId: string;data: MergeTagBody},
        TContext
      > => {

      const mutationOptions = getMergeTagApiV1TagsTagIdMergePostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Tag Entities
 */
export const listTagEntitiesApiV1TagsEntitiesGet = (
    params?: ListTagEntitiesApiV1TagsEntitiesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TaggedEntityResponse[]>(
      {url: `/api/v1/tags/entities`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListTagEntitiesApiV1TagsEntitiesGetQueryKey = (params?: ListTagEntitiesApiV1TagsEntitiesGetParams,) => {
    return [
    `/api/v1/tags/entities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTagEntitiesApiV1TagsEntitiesGetQueryOptions = <TData = Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError = HTTPValidationError>(params?: ListTagEntitiesApiV1TagsEntitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagEntitiesApiV1TagsEntitiesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>> = ({ signal }) => listTagEntitiesApiV1TagsEntitiesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTagEntitiesApiV1TagsEntitiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>>
export type ListTagEntitiesApiV1TagsEntitiesGetQueryError = HTTPValidationError


export function useListTagEntitiesApiV1TagsEntitiesGet<TData = Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTagEntitiesApiV1TagsEntitiesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>,
          TError,
          Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTagEntitiesApiV1TagsEntitiesGet<TData = Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError = HTTPValidationError>(
 params?: ListTagEntitiesApiV1TagsEntitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>,
          TError,
          Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTagEntitiesApiV1TagsEntitiesGet<TData = Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError = HTTPValidationError>(
 params?: ListTagEntitiesApiV1TagsEntitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tag Entities
 */

export function useListTagEntitiesApiV1TagsEntitiesGet<TData = Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError = HTTPValidationError>(
 params?: ListTagEntitiesApiV1TagsEntitiesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTagEntitiesApiV1TagsEntitiesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTagEntitiesApiV1TagsEntitiesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Entity Tags
 */
export const getEntityTagsApiV1EntityCollectionEntityIdTagsGet = (
    entityCollection: string,
    entityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<EntityTagResponse[]>(
      {url: `/api/v1/${entityCollection}/${entityId}/tags`, method: 'GET', signal
    },
      );
    }
  



export const getGetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryKey = (entityCollection?: string,
    entityId?: string,) => {
    return [
    `/api/v1/${entityCollection}/${entityId}/tags`
    ] as const;
    }

    
export const getGetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryOptions = <TData = Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError = HTTPValidationError>(entityCollection: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryKey(entityCollection,entityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>> = ({ signal }) => getEntityTagsApiV1EntityCollectionEntityIdTagsGet(entityCollection,entityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(entityCollection && entityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>>
export type GetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryError = HTTPValidationError


export function useGetEntityTagsApiV1EntityCollectionEntityIdTagsGet<TData = Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError = HTTPValidationError>(
 entityCollection: string,
    entityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>,
          TError,
          Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntityTagsApiV1EntityCollectionEntityIdTagsGet<TData = Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError = HTTPValidationError>(
 entityCollection: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>,
          TError,
          Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntityTagsApiV1EntityCollectionEntityIdTagsGet<TData = Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError = HTTPValidationError>(
 entityCollection: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Entity Tags
 */

export function useGetEntityTagsApiV1EntityCollectionEntityIdTagsGet<TData = Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError = HTTPValidationError>(
 entityCollection: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntityTagsApiV1EntityCollectionEntityIdTagsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntityTagsApiV1EntityCollectionEntityIdTagsGetQueryOptions(entityCollection,entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Assign Entity Tag
 */
export const assignEntityTagApiV1EntityCollectionEntityIdTagsPost = (
    entityCollection: string,
    entityId: string,
    assignTagBody: AssignTagBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TagResponse>(
      {url: `/api/v1/${entityCollection}/${entityId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignTagBody, signal
    },
      );
    }
  


export const getAssignEntityTagApiV1EntityCollectionEntityIdTagsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>, TError,{entityCollection: string;entityId: string;data: AssignTagBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>, TError,{entityCollection: string;entityId: string;data: AssignTagBody}, TContext> => {

const mutationKey = ['assignEntityTagApiV1EntityCollectionEntityIdTagsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>, {entityCollection: string;entityId: string;data: AssignTagBody}> = (props) => {
          const {entityCollection,entityId,data} = props ?? {};

          return  assignEntityTagApiV1EntityCollectionEntityIdTagsPost(entityCollection,entityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignEntityTagApiV1EntityCollectionEntityIdTagsPostMutationResult = NonNullable<Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>>
    export type AssignEntityTagApiV1EntityCollectionEntityIdTagsPostMutationBody = AssignTagBody
    export type AssignEntityTagApiV1EntityCollectionEntityIdTagsPostMutationError = HTTPValidationError

    /**
 * @summary Assign Entity Tag
 */
export const useAssignEntityTagApiV1EntityCollectionEntityIdTagsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>, TError,{entityCollection: string;entityId: string;data: AssignTagBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignEntityTagApiV1EntityCollectionEntityIdTagsPost>>,
        TError,
        {entityCollection: string;entityId: string;data: AssignTagBody},
        TContext
      > => {

      const mutationOptions = getAssignEntityTagApiV1EntityCollectionEntityIdTagsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Set Entity Tags
 */
export const setEntityTagsApiV1EntityCollectionEntityIdTagsPut = (
    entityCollection: string,
    entityId: string,
    setEntityTagsBody: SetEntityTagsBody,
 ) => {
      
      
      return customInstance<TagResponse[]>(
      {url: `/api/v1/${entityCollection}/${entityId}/tags`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setEntityTagsBody
    },
      );
    }
  


export const getSetEntityTagsApiV1EntityCollectionEntityIdTagsPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>, TError,{entityCollection: string;entityId: string;data: SetEntityTagsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>, TError,{entityCollection: string;entityId: string;data: SetEntityTagsBody}, TContext> => {

const mutationKey = ['setEntityTagsApiV1EntityCollectionEntityIdTagsPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>, {entityCollection: string;entityId: string;data: SetEntityTagsBody}> = (props) => {
          const {entityCollection,entityId,data} = props ?? {};

          return  setEntityTagsApiV1EntityCollectionEntityIdTagsPut(entityCollection,entityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetEntityTagsApiV1EntityCollectionEntityIdTagsPutMutationResult = NonNullable<Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>>
    export type SetEntityTagsApiV1EntityCollectionEntityIdTagsPutMutationBody = SetEntityTagsBody
    export type SetEntityTagsApiV1EntityCollectionEntityIdTagsPutMutationError = HTTPValidationError

    /**
 * @summary Set Entity Tags
 */
export const useSetEntityTagsApiV1EntityCollectionEntityIdTagsPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>, TError,{entityCollection: string;entityId: string;data: SetEntityTagsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setEntityTagsApiV1EntityCollectionEntityIdTagsPut>>,
        TError,
        {entityCollection: string;entityId: string;data: SetEntityTagsBody},
        TContext
      > => {

      const mutationOptions = getSetEntityTagsApiV1EntityCollectionEntityIdTagsPutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Unassign Entity Tag
 */
export const unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete = (
    entityCollection: string,
    entityId: string,
    tagId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/${entityCollection}/${entityId}/tags/${tagId}`, method: 'DELETE'
    },
      );
    }
  


export const getUnassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>, TError,{entityCollection: string;entityId: string;tagId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>, TError,{entityCollection: string;entityId: string;tagId: string}, TContext> => {

const mutationKey = ['unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>, {entityCollection: string;entityId: string;tagId: string}> = (props) => {
          const {entityCollection,entityId,tagId} = props ?? {};

          return  unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete(entityCollection,entityId,tagId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>>
    
    export type UnassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Unassign Entity Tag
 */
export const useUnassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>, TError,{entityCollection: string;entityId: string;tagId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDelete>>,
        TError,
        {entityCollection: string;entityId: string;tagId: string},
        TContext
      > => {

      const mutationOptions = getUnassignEntityTagApiV1EntityCollectionEntityIdTagsTagIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    