"""Interface-layer dependency injection exports."""

from protcellar.interface.dependencies._core import (
    AuthDep,
    EventDispatcherDep,
    UoWDep,
    _get_use_case,
    get_auth,
    get_container,
    get_event_dispatcher,
    get_uow,
)
from protcellar.interface.dependencies._protein_catalog import (
    BulkUpsertProteinsDep,
    CreateGeneDep,
    CreateProteinDep,
    GetGeneDep,
    GetProteinDep,
    ListGenesDep,
    ListProteinsDep,
    ResolveProteinIdDep,
    UpdateGeneDep,
    UpdateProteinDep,
)
from protcellar.interface.dependencies._taxonomy import (
    BulkUpsertOrganismsDep,
    CreateOrganismDep,
    CreateProteomeDep,
    CreateStrainDep,
    GetOrganismDep,
    GetProteomeDep,
    GetStrainDep,
    ListOrganismsDep,
    ListProteomesDep,
    ListStrainsDep,
    ResolveTaxIdDep,
    UpdateOrganismDep,
    UpdateStrainDep,
)
from protcellar.interface.dependencies._workspace_config import (
    CreateOrganizationDep,
    GetOrganizationDep,
    ListOrganizationsDep,
    UpdateOrganizationDep,
)

__all__ = [
    "AuthDep",
    "BulkUpsertOrganismsDep",
    "BulkUpsertProteinsDep",
    "CreateGeneDep",
    "CreateOrganismDep",
    "CreateOrganizationDep",
    "CreateProteinDep",
    "CreateProteomeDep",
    "CreateStrainDep",
    "EventDispatcherDep",
    "GetGeneDep",
    "GetOrganismDep",
    "GetOrganizationDep",
    "GetProteinDep",
    "GetProteomeDep",
    "GetStrainDep",
    "ListGenesDep",
    "ListOrganismsDep",
    "ListOrganizationsDep",
    "ListProteinsDep",
    "ListProteomesDep",
    "ListStrainsDep",
    "ResolveProteinIdDep",
    "ResolveTaxIdDep",
    "UoWDep",
    "UpdateGeneDep",
    "UpdateOrganismDep",
    "UpdateOrganizationDep",
    "UpdateProteinDep",
    "UpdateStrainDep",
    "_get_use_case",
    "get_auth",
    "get_container",
    "get_event_dispatcher",
    "get_uow",
]
