"""Interface-layer dependency injection exports."""

from protcellar.interface.dependencies._core import (
    AuthDep,
    EventDispatcherDep,
    UoWDep,
    _get_use_case,
    get_auth,
    get_container,
    get_event_dispatcher,
    get_uow,
)
from protcellar.interface.dependencies._imports import (
    GetImportRunDep,
    GetUploadDep,
    ListImportRunsDep,
    StartImportDep,
    StoreUploadDep,
)
from protcellar.interface.dependencies._protein_catalog import (
    BulkUpsertGenesDep,
    BulkUpsertProteinsDep,
    CreateGeneDep,
    CreateProteinDep,
    GetGeneDep,
    GetGeneNeighborhoodDep,
    GetProteinDep,
    ListGenesDep,
    ListProteinsDep,
    ResolveProteinIdDep,
    UpdateGeneDep,
    UpdateProteinDep,
)
from protcellar.interface.dependencies._target import (
    CreateTargetDep,
    GetTargetDep,
    ListTargetsDep,
    UpdateTargetDep,
)
from protcellar.interface.dependencies._target_biology import (
    GetGeneTargetBiologyDep,
    GetProteinTargetBiologyDep,
)
from protcellar.interface.dependencies._taxonomy import (
    BulkUpsertOrganismsDep,
    CreateOrganismDep,
    CreateProteomeDep,
    CreateStrainDep,
    GetOrganismDep,
    GetProteomeDep,
    GetStrainDep,
    ListOrganismsDep,
    ListProteomesDep,
    ListStrainsDep,
    ResolveTaxIdDep,
    UpdateOrganismDep,
    UpdateStrainDep,
)
from protcellar.interface.dependencies._workspace_config import (
    CreateOrganizationDep,
    GetOrganizationDep,
    ListOrganizationsDep,
    UpdateOrganizationDep,
)

__all__ = [
    "AuthDep",
    "BulkUpsertGenesDep",
    "BulkUpsertOrganismsDep",
    "BulkUpsertProteinsDep",
    "CreateGeneDep",
    "CreateOrganismDep",
    "CreateOrganizationDep",
    "CreateProteinDep",
    "CreateProteomeDep",
    "CreateStrainDep",
    "CreateTargetDep",
    "EventDispatcherDep",
    "GetGeneDep",
    "GetGeneNeighborhoodDep",
    "GetGeneTargetBiologyDep",
    "GetImportRunDep",
    "GetOrganismDep",
    "GetOrganizationDep",
    "GetProteinDep",
    "GetProteinTargetBiologyDep",
    "GetProteomeDep",
    "GetStrainDep",
    "GetTargetDep",
    "GetUploadDep",
    "ListGenesDep",
    "ListImportRunsDep",
    "ListOrganismsDep",
    "ListOrganizationsDep",
    "ListProteinsDep",
    "ListProteomesDep",
    "ListStrainsDep",
    "ListTargetsDep",
    "ResolveProteinIdDep",
    "ResolveTaxIdDep",
    "StartImportDep",
    "StoreUploadDep",
    "UoWDep",
    "UpdateGeneDep",
    "UpdateOrganismDep",
    "UpdateOrganizationDep",
    "UpdateProteinDep",
    "UpdateStrainDep",
    "UpdateTargetDep",
    "_get_use_case",
    "get_auth",
    "get_container",
    "get_event_dispatcher",
    "get_uow",
]
