/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkUpsertResponse,
  CreateOrganismBody,
  HTTPValidationError,
  ListOrganismsApiV1OrganismsGetParams,
  OrganismResponse,
  PaginatedResponseOrganismResponse,
  ProtcellarInterfaceRoutesOrganismsBulkUpsertBody,
  UpdateOrganismBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Resolve Organism
 */
export const resolveOrganismApiV1OrganismsResolveTaxIdGet = (
    taxId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OrganismResponse>(
      {url: `/api/v1/organisms/resolve/${taxId}`, method: 'GET', signal
    },
      );
    }
  



export const getResolveOrganismApiV1OrganismsResolveTaxIdGetQueryKey = (taxId?: number,) => {
    return [
    `/api/v1/organisms/resolve/${taxId}`
    ] as const;
    }

    
export const getResolveOrganismApiV1OrganismsResolveTaxIdGetQueryOptions = <TData = Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError = HTTPValidationError>(taxId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveOrganismApiV1OrganismsResolveTaxIdGetQueryKey(taxId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>> = ({ signal }) => resolveOrganismApiV1OrganismsResolveTaxIdGet(taxId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taxId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveOrganismApiV1OrganismsResolveTaxIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>>
export type ResolveOrganismApiV1OrganismsResolveTaxIdGetQueryError = HTTPValidationError


export function useResolveOrganismApiV1OrganismsResolveTaxIdGet<TData = Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError = HTTPValidationError>(
 taxId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>,
          TError,
          Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveOrganismApiV1OrganismsResolveTaxIdGet<TData = Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError = HTTPValidationError>(
 taxId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>,
          TError,
          Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveOrganismApiV1OrganismsResolveTaxIdGet<TData = Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError = HTTPValidationError>(
 taxId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve Organism
 */

export function useResolveOrganismApiV1OrganismsResolveTaxIdGet<TData = Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError = HTTPValidationError>(
 taxId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveOrganismApiV1OrganismsResolveTaxIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveOrganismApiV1OrganismsResolveTaxIdGetQueryOptions(taxId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Organisms
 */
export const listOrganismsApiV1OrganismsGet = (
    params?: ListOrganismsApiV1OrganismsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseOrganismResponse>(
      {url: `/api/v1/organisms`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListOrganismsApiV1OrganismsGetQueryKey = (params?: ListOrganismsApiV1OrganismsGetParams,) => {
    return [
    `/api/v1/organisms`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListOrganismsApiV1OrganismsGetQueryOptions = <TData = Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError = HTTPValidationError>(params?: ListOrganismsApiV1OrganismsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOrganismsApiV1OrganismsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>> = ({ signal }) => listOrganismsApiV1OrganismsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOrganismsApiV1OrganismsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>>
export type ListOrganismsApiV1OrganismsGetQueryError = HTTPValidationError


export function useListOrganismsApiV1OrganismsGet<TData = Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListOrganismsApiV1OrganismsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>,
          TError,
          Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOrganismsApiV1OrganismsGet<TData = Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError = HTTPValidationError>(
 params?: ListOrganismsApiV1OrganismsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>,
          TError,
          Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOrganismsApiV1OrganismsGet<TData = Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError = HTTPValidationError>(
 params?: ListOrganismsApiV1OrganismsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Organisms
 */

export function useListOrganismsApiV1OrganismsGet<TData = Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError = HTTPValidationError>(
 params?: ListOrganismsApiV1OrganismsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganismsApiV1OrganismsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOrganismsApiV1OrganismsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Organism
 */
export const createOrganismApiV1OrganismsPost = (
    createOrganismBody: CreateOrganismBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OrganismResponse>(
      {url: `/api/v1/organisms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrganismBody, signal
    },
      );
    }
  


export const getCreateOrganismApiV1OrganismsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>, TError,{data: CreateOrganismBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>, TError,{data: CreateOrganismBody}, TContext> => {

const mutationKey = ['createOrganismApiV1OrganismsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>, {data: CreateOrganismBody}> = (props) => {
          const {data} = props ?? {};

          return  createOrganismApiV1OrganismsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganismApiV1OrganismsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>>
    export type CreateOrganismApiV1OrganismsPostMutationBody = CreateOrganismBody
    export type CreateOrganismApiV1OrganismsPostMutationError = HTTPValidationError

    /**
 * @summary Create Organism
 */
export const useCreateOrganismApiV1OrganismsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>, TError,{data: CreateOrganismBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrganismApiV1OrganismsPost>>,
        TError,
        {data: CreateOrganismBody},
        TContext
      > => {

      const mutationOptions = getCreateOrganismApiV1OrganismsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Organism
 */
export const getOrganismApiV1OrganismsOrganismIdGet = (
    organismId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OrganismResponse>(
      {url: `/api/v1/organisms/${organismId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrganismApiV1OrganismsOrganismIdGetQueryKey = (organismId?: string,) => {
    return [
    `/api/v1/organisms/${organismId}`
    ] as const;
    }

    
export const getGetOrganismApiV1OrganismsOrganismIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError = HTTPValidationError>(organismId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganismApiV1OrganismsOrganismIdGetQueryKey(organismId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>> = ({ signal }) => getOrganismApiV1OrganismsOrganismIdGet(organismId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(organismId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganismApiV1OrganismsOrganismIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>>
export type GetOrganismApiV1OrganismsOrganismIdGetQueryError = HTTPValidationError


export function useGetOrganismApiV1OrganismsOrganismIdGet<TData = Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError = HTTPValidationError>(
 organismId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganismApiV1OrganismsOrganismIdGet<TData = Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError = HTTPValidationError>(
 organismId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganismApiV1OrganismsOrganismIdGet<TData = Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError = HTTPValidationError>(
 organismId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Organism
 */

export function useGetOrganismApiV1OrganismsOrganismIdGet<TData = Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError = HTTPValidationError>(
 organismId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganismApiV1OrganismsOrganismIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganismApiV1OrganismsOrganismIdGetQueryOptions(organismId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Organism
 */
export const updateOrganismApiV1OrganismsOrganismIdPatch = (
    organismId: string,
    updateOrganismBody: UpdateOrganismBody,
 ) => {
      
      
      return customInstance<OrganismResponse>(
      {url: `/api/v1/organisms/${organismId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganismBody
    },
      );
    }
  


export const getUpdateOrganismApiV1OrganismsOrganismIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>, TError,{organismId: string;data: UpdateOrganismBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>, TError,{organismId: string;data: UpdateOrganismBody}, TContext> => {

const mutationKey = ['updateOrganismApiV1OrganismsOrganismIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>, {organismId: string;data: UpdateOrganismBody}> = (props) => {
          const {organismId,data} = props ?? {};

          return  updateOrganismApiV1OrganismsOrganismIdPatch(organismId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganismApiV1OrganismsOrganismIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>>
    export type UpdateOrganismApiV1OrganismsOrganismIdPatchMutationBody = UpdateOrganismBody
    export type UpdateOrganismApiV1OrganismsOrganismIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Organism
 */
export const useUpdateOrganismApiV1OrganismsOrganismIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>, TError,{organismId: string;data: UpdateOrganismBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganismApiV1OrganismsOrganismIdPatch>>,
        TError,
        {organismId: string;data: UpdateOrganismBody},
        TContext
      > => {

      const mutationOptions = getUpdateOrganismApiV1OrganismsOrganismIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Bulk Upsert Organisms
 */
export const bulkUpsertOrganismsApiV1OrganismsBulkPost = (
    protcellarInterfaceRoutesOrganismsBulkUpsertBody: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BulkUpsertResponse>(
      {url: `/api/v1/organisms/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: protcellarInterfaceRoutesOrganismsBulkUpsertBody, signal
    },
      );
    }
  


export const getBulkUpsertOrganismsApiV1OrganismsBulkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody}, TContext> => {

const mutationKey = ['bulkUpsertOrganismsApiV1OrganismsBulkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>, {data: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody}> = (props) => {
          const {data} = props ?? {};

          return  bulkUpsertOrganismsApiV1OrganismsBulkPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkUpsertOrganismsApiV1OrganismsBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>>
    export type BulkUpsertOrganismsApiV1OrganismsBulkPostMutationBody = ProtcellarInterfaceRoutesOrganismsBulkUpsertBody
    export type BulkUpsertOrganismsApiV1OrganismsBulkPostMutationError = HTTPValidationError

    /**
 * @summary Bulk Upsert Organisms
 */
export const useBulkUpsertOrganismsApiV1OrganismsBulkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkUpsertOrganismsApiV1OrganismsBulkPost>>,
        TError,
        {data: ProtcellarInterfaceRoutesOrganismsBulkUpsertBody},
        TContext
      > => {

      const mutationOptions = getBulkUpsertOrganismsApiV1OrganismsBulkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    