/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VersionResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Version
 */
export const versionVersionGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<VersionResponse>(
      {url: `/version`, method: 'GET', signal
    },
      );
    }
  



export const getVersionVersionGetQueryKey = () => {
    return [
    `/version`
    ] as const;
    }

    
export const getVersionVersionGetQueryOptions = <TData = Awaited<ReturnType<typeof versionVersionGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVersionVersionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof versionVersionGet>>> = ({ signal }) => versionVersionGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VersionVersionGetQueryResult = NonNullable<Awaited<ReturnType<typeof versionVersionGet>>>
export type VersionVersionGetQueryError = unknown


export function useVersionVersionGet<TData = Awaited<ReturnType<typeof versionVersionGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof versionVersionGet>>,
          TError,
          Awaited<ReturnType<typeof versionVersionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVersionVersionGet<TData = Awaited<ReturnType<typeof versionVersionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof versionVersionGet>>,
          TError,
          Awaited<ReturnType<typeof versionVersionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVersionVersionGet<TData = Awaited<ReturnType<typeof versionVersionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Version
 */

export function useVersionVersionGet<TData = Awaited<ReturnType<typeof versionVersionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof versionVersionGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVersionVersionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




