/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOrganizationBody,
  HTTPValidationError,
  ListOrganizationsApiV1OrganizationsGetParams,
  OrganizationResponse,
  PaginatedResponseOrganizationResponse,
  UpdateOrganizationBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Organizations
 */
export const listOrganizationsApiV1OrganizationsGet = (
    params?: ListOrganizationsApiV1OrganizationsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseOrganizationResponse>(
      {url: `/api/v1/organizations`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListOrganizationsApiV1OrganizationsGetQueryKey = (params?: ListOrganizationsApiV1OrganizationsGetParams,) => {
    return [
    `/api/v1/organizations`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListOrganizationsApiV1OrganizationsGetQueryOptions = <TData = Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError = HTTPValidationError>(params?: ListOrganizationsApiV1OrganizationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOrganizationsApiV1OrganizationsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>> = ({ signal }) => listOrganizationsApiV1OrganizationsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOrganizationsApiV1OrganizationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>>
export type ListOrganizationsApiV1OrganizationsGetQueryError = HTTPValidationError


export function useListOrganizationsApiV1OrganizationsGet<TData = Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListOrganizationsApiV1OrganizationsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>,
          TError,
          Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOrganizationsApiV1OrganizationsGet<TData = Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError = HTTPValidationError>(
 params?: ListOrganizationsApiV1OrganizationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>,
          TError,
          Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListOrganizationsApiV1OrganizationsGet<TData = Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError = HTTPValidationError>(
 params?: ListOrganizationsApiV1OrganizationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Organizations
 */

export function useListOrganizationsApiV1OrganizationsGet<TData = Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError = HTTPValidationError>(
 params?: ListOrganizationsApiV1OrganizationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listOrganizationsApiV1OrganizationsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListOrganizationsApiV1OrganizationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Organization
 */
export const createOrganizationApiV1OrganizationsPost = (
    createOrganizationBody: CreateOrganizationBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationResponse>(
      {url: `/api/v1/organizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrganizationBody, signal
    },
      );
    }
  


export const getCreateOrganizationApiV1OrganizationsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>, TError,{data: CreateOrganizationBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>, TError,{data: CreateOrganizationBody}, TContext> => {

const mutationKey = ['createOrganizationApiV1OrganizationsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>, {data: CreateOrganizationBody}> = (props) => {
          const {data} = props ?? {};

          return  createOrganizationApiV1OrganizationsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationApiV1OrganizationsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>>
    export type CreateOrganizationApiV1OrganizationsPostMutationBody = CreateOrganizationBody
    export type CreateOrganizationApiV1OrganizationsPostMutationError = HTTPValidationError

    /**
 * @summary Create Organization
 */
export const useCreateOrganizationApiV1OrganizationsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>, TError,{data: CreateOrganizationBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrganizationApiV1OrganizationsPost>>,
        TError,
        {data: CreateOrganizationBody},
        TContext
      > => {

      const mutationOptions = getCreateOrganizationApiV1OrganizationsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Organization
 */
export const getOrganizationApiV1OrganizationsOrgIdGet = (
    orgId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationResponse>(
      {url: `/api/v1/organizations/${orgId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrganizationApiV1OrganizationsOrgIdGetQueryKey = (orgId?: string,) => {
    return [
    `/api/v1/organizations/${orgId}`
    ] as const;
    }

    
export const getGetOrganizationApiV1OrganizationsOrgIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError = HTTPValidationError>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationApiV1OrganizationsOrgIdGetQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>> = ({ signal }) => getOrganizationApiV1OrganizationsOrgIdGet(orgId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationApiV1OrganizationsOrgIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>>
export type GetOrganizationApiV1OrganizationsOrgIdGetQueryError = HTTPValidationError


export function useGetOrganizationApiV1OrganizationsOrgIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError = HTTPValidationError>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationApiV1OrganizationsOrgIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationApiV1OrganizationsOrgIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Organization
 */

export function useGetOrganizationApiV1OrganizationsOrgIdGet<TData = Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationApiV1OrganizationsOrgIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationApiV1OrganizationsOrgIdGetQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Organization
 */
export const updateOrganizationApiV1OrganizationsOrgIdPatch = (
    orgId: string,
    updateOrganizationBody: UpdateOrganizationBody,
 ) => {
      
      
      return customInstance<OrganizationResponse>(
      {url: `/api/v1/organizations/${orgId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganizationBody
    },
      );
    }
  


export const getUpdateOrganizationApiV1OrganizationsOrgIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>, TError,{orgId: string;data: UpdateOrganizationBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>, TError,{orgId: string;data: UpdateOrganizationBody}, TContext> => {

const mutationKey = ['updateOrganizationApiV1OrganizationsOrgIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>, {orgId: string;data: UpdateOrganizationBody}> = (props) => {
          const {orgId,data} = props ?? {};

          return  updateOrganizationApiV1OrganizationsOrgIdPatch(orgId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationApiV1OrganizationsOrgIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>>
    export type UpdateOrganizationApiV1OrganizationsOrgIdPatchMutationBody = UpdateOrganizationBody
    export type UpdateOrganizationApiV1OrganizationsOrgIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Organization
 */
export const useUpdateOrganizationApiV1OrganizationsOrgIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>, TError,{orgId: string;data: UpdateOrganizationBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganizationApiV1OrganizationsOrgIdPatch>>,
        TError,
        {orgId: string;data: UpdateOrganizationBody},
        TContext
      > => {

      const mutationOptions = getUpdateOrganizationApiV1OrganizationsOrgIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    