/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFieldDefBody,
  ExtensionFieldDefResponse,
  HTTPValidationError,
  ListFieldDefsApiV1ExtensionFieldsGetParams,
  UpdateFieldDefBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Field Defs
 */
export const listFieldDefsApiV1ExtensionFieldsGet = (
    params?: ListFieldDefsApiV1ExtensionFieldsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ExtensionFieldDefResponse[]>(
      {url: `/api/v1/extension-fields`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListFieldDefsApiV1ExtensionFieldsGetQueryKey = (params?: ListFieldDefsApiV1ExtensionFieldsGetParams,) => {
    return [
    `/api/v1/extension-fields`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListFieldDefsApiV1ExtensionFieldsGetQueryOptions = <TData = Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError = HTTPValidationError>(params?: ListFieldDefsApiV1ExtensionFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFieldDefsApiV1ExtensionFieldsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>> = ({ signal }) => listFieldDefsApiV1ExtensionFieldsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFieldDefsApiV1ExtensionFieldsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>>
export type ListFieldDefsApiV1ExtensionFieldsGetQueryError = HTTPValidationError


export function useListFieldDefsApiV1ExtensionFieldsGet<TData = Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListFieldDefsApiV1ExtensionFieldsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>,
          TError,
          Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFieldDefsApiV1ExtensionFieldsGet<TData = Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError = HTTPValidationError>(
 params?: ListFieldDefsApiV1ExtensionFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>,
          TError,
          Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFieldDefsApiV1ExtensionFieldsGet<TData = Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError = HTTPValidationError>(
 params?: ListFieldDefsApiV1ExtensionFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Field Defs
 */

export function useListFieldDefsApiV1ExtensionFieldsGet<TData = Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError = HTTPValidationError>(
 params?: ListFieldDefsApiV1ExtensionFieldsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFieldDefsApiV1ExtensionFieldsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFieldDefsApiV1ExtensionFieldsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Field Def
 */
export const createFieldDefApiV1ExtensionFieldsPost = (
    createFieldDefBody: CreateFieldDefBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ExtensionFieldDefResponse>(
      {url: `/api/v1/extension-fields`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFieldDefBody, signal
    },
      );
    }
  


export const getCreateFieldDefApiV1ExtensionFieldsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>, TError,{data: CreateFieldDefBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>, TError,{data: CreateFieldDefBody}, TContext> => {

const mutationKey = ['createFieldDefApiV1ExtensionFieldsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>, {data: CreateFieldDefBody}> = (props) => {
          const {data} = props ?? {};

          return  createFieldDefApiV1ExtensionFieldsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateFieldDefApiV1ExtensionFieldsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>>
    export type CreateFieldDefApiV1ExtensionFieldsPostMutationBody = CreateFieldDefBody
    export type CreateFieldDefApiV1ExtensionFieldsPostMutationError = HTTPValidationError

    /**
 * @summary Create Field Def
 */
export const useCreateFieldDefApiV1ExtensionFieldsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>, TError,{data: CreateFieldDefBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFieldDefApiV1ExtensionFieldsPost>>,
        TError,
        {data: CreateFieldDefBody},
        TContext
      > => {

      const mutationOptions = getCreateFieldDefApiV1ExtensionFieldsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Field Def
 */
export const updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch = (
    fieldDefId: string,
    updateFieldDefBody: UpdateFieldDefBody,
 ) => {
      
      
      return customInstance<ExtensionFieldDefResponse>(
      {url: `/api/v1/extension-fields/${fieldDefId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFieldDefBody
    },
      );
    }
  


export const getUpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>, TError,{fieldDefId: string;data: UpdateFieldDefBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>, TError,{fieldDefId: string;data: UpdateFieldDefBody}, TContext> => {

const mutationKey = ['updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>, {fieldDefId: string;data: UpdateFieldDefBody}> = (props) => {
          const {fieldDefId,data} = props ?? {};

          return  updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch(fieldDefId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>>
    export type UpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatchMutationBody = UpdateFieldDefBody
    export type UpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Field Def
 */
export const useUpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>, TError,{fieldDefId: string;data: UpdateFieldDefBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFieldDefApiV1ExtensionFieldsFieldDefIdPatch>>,
        TError,
        {fieldDefId: string;data: UpdateFieldDefBody},
        TContext
      > => {

      const mutationOptions = getUpdateFieldDefApiV1ExtensionFieldsFieldDefIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Field Def
 */
export const deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete = (
    fieldDefId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/extension-fields/${fieldDefId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteFieldDefApiV1ExtensionFieldsFieldDefIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>, TError,{fieldDefId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>, TError,{fieldDefId: string}, TContext> => {

const mutationKey = ['deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>, {fieldDefId: string}> = (props) => {
          const {fieldDefId} = props ?? {};

          return  deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete(fieldDefId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFieldDefApiV1ExtensionFieldsFieldDefIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>>
    
    export type DeleteFieldDefApiV1ExtensionFieldsFieldDefIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Field Def
 */
export const useDeleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>, TError,{fieldDefId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFieldDefApiV1ExtensionFieldsFieldDefIdDelete>>,
        TError,
        {fieldDefId: string},
        TContext
      > => {

      const mutationOptions = getDeleteFieldDefApiV1ExtensionFieldsFieldDefIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    