/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GeneTargetBiologyResponse,
  HTTPValidationError,
  ProteinTargetBiologyResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Get Gene Target Biology
 */
export const getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet = (
    geneId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GeneTargetBiologyResponse>(
      {url: `/api/v1/genes/${geneId}/target-biology`, method: 'GET', signal
    },
      );
    }
  



export const getGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryKey = (geneId?: string,) => {
    return [
    `/api/v1/genes/${geneId}/target-biology`
    ] as const;
    }

    
export const getGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryOptions = <TData = Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError = HTTPValidationError>(geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryKey(geneId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>> = ({ signal }) => getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet(geneId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(geneId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>>
export type GetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryError = HTTPValidationError


export function useGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError = HTTPValidationError>(
 geneId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>,
          TError,
          Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>,
          TError,
          Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Gene Target Biology
 */

export function useGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError = HTTPValidationError>(
 geneId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGeneTargetBiologyApiV1GenesGeneIdTargetBiologyGetQueryOptions(geneId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Protein Target Biology
 */
export const getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet = (
    proteinId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProteinTargetBiologyResponse>(
      {url: `/api/v1/proteins/${proteinId}/target-biology`, method: 'GET', signal
    },
      );
    }
  



export const getGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryKey = (proteinId?: string,) => {
    return [
    `/api/v1/proteins/${proteinId}/target-biology`
    ] as const;
    }

    
export const getGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryOptions = <TData = Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError = HTTPValidationError>(proteinId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryKey(proteinId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>> = ({ signal }) => getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet(proteinId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(proteinId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>>
export type GetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryError = HTTPValidationError


export function useGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError = HTTPValidationError>(
 proteinId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>,
          TError,
          Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError = HTTPValidationError>(
 proteinId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>,
          TError,
          Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError = HTTPValidationError>(
 proteinId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Protein Target Biology
 */

export function useGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet<TData = Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError = HTTPValidationError>(
 proteinId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProteinTargetBiologyApiV1ProteinsProteinIdTargetBiologyGetQueryOptions(proteinId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




