/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkUpsertResponse,
  CreateProteinBody,
  GetProteinApiV1ProteinsAccessionGetParams,
  HTTPValidationError,
  ListProteinsApiV1ProteinsGetParams,
  PaginatedResponseProteinResponse,
  ProtcellarInterfaceRoutesProteinsBulkUpsertBody,
  ProteinResponse,
  UpdateProteinBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Resolve Protein
 */
export const resolveProteinApiV1ProteinsResolveIdentifierGet = (
    identifier: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProteinResponse>(
      {url: `/api/v1/proteins/resolve/${identifier}`, method: 'GET', signal
    },
      );
    }
  



export const getResolveProteinApiV1ProteinsResolveIdentifierGetQueryKey = (identifier?: string,) => {
    return [
    `/api/v1/proteins/resolve/${identifier}`
    ] as const;
    }

    
export const getResolveProteinApiV1ProteinsResolveIdentifierGetQueryOptions = <TData = Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError = HTTPValidationError>(identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveProteinApiV1ProteinsResolveIdentifierGetQueryKey(identifier);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>> = ({ signal }) => resolveProteinApiV1ProteinsResolveIdentifierGet(identifier, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(identifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveProteinApiV1ProteinsResolveIdentifierGetQueryResult = NonNullable<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>>
export type ResolveProteinApiV1ProteinsResolveIdentifierGetQueryError = HTTPValidationError


export function useResolveProteinApiV1ProteinsResolveIdentifierGet<TData = Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>,
          TError,
          Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveProteinApiV1ProteinsResolveIdentifierGet<TData = Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>,
          TError,
          Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveProteinApiV1ProteinsResolveIdentifierGet<TData = Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve Protein
 */

export function useResolveProteinApiV1ProteinsResolveIdentifierGet<TData = Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError = HTTPValidationError>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveProteinApiV1ProteinsResolveIdentifierGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveProteinApiV1ProteinsResolveIdentifierGetQueryOptions(identifier,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List Proteins
 */
export const listProteinsApiV1ProteinsGet = (
    params?: ListProteinsApiV1ProteinsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProteinResponse>(
      {url: `/api/v1/proteins`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListProteinsApiV1ProteinsGetQueryKey = (params?: ListProteinsApiV1ProteinsGetParams,) => {
    return [
    `/api/v1/proteins`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProteinsApiV1ProteinsGetQueryOptions = <TData = Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError = HTTPValidationError>(params?: ListProteinsApiV1ProteinsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProteinsApiV1ProteinsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>> = ({ signal }) => listProteinsApiV1ProteinsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProteinsApiV1ProteinsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>>
export type ListProteinsApiV1ProteinsGetQueryError = HTTPValidationError


export function useListProteinsApiV1ProteinsGet<TData = Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListProteinsApiV1ProteinsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>,
          TError,
          Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProteinsApiV1ProteinsGet<TData = Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError = HTTPValidationError>(
 params?: ListProteinsApiV1ProteinsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>,
          TError,
          Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProteinsApiV1ProteinsGet<TData = Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError = HTTPValidationError>(
 params?: ListProteinsApiV1ProteinsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Proteins
 */

export function useListProteinsApiV1ProteinsGet<TData = Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError = HTTPValidationError>(
 params?: ListProteinsApiV1ProteinsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteinsApiV1ProteinsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProteinsApiV1ProteinsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Protein
 */
export const createProteinApiV1ProteinsPost = (
    createProteinBody: CreateProteinBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProteinResponse>(
      {url: `/api/v1/proteins`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProteinBody, signal
    },
      );
    }
  


export const getCreateProteinApiV1ProteinsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>, TError,{data: CreateProteinBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>, TError,{data: CreateProteinBody}, TContext> => {

const mutationKey = ['createProteinApiV1ProteinsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>, {data: CreateProteinBody}> = (props) => {
          const {data} = props ?? {};

          return  createProteinApiV1ProteinsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProteinApiV1ProteinsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>>
    export type CreateProteinApiV1ProteinsPostMutationBody = CreateProteinBody
    export type CreateProteinApiV1ProteinsPostMutationError = HTTPValidationError

    /**
 * @summary Create Protein
 */
export const useCreateProteinApiV1ProteinsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>, TError,{data: CreateProteinBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProteinApiV1ProteinsPost>>,
        TError,
        {data: CreateProteinBody},
        TContext
      > => {

      const mutationOptions = getCreateProteinApiV1ProteinsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Bulk Upsert Proteins
 */
export const bulkUpsertProteinsApiV1ProteinsBulkPost = (
    protcellarInterfaceRoutesProteinsBulkUpsertBody: ProtcellarInterfaceRoutesProteinsBulkUpsertBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BulkUpsertResponse>(
      {url: `/api/v1/proteins/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: protcellarInterfaceRoutesProteinsBulkUpsertBody, signal
    },
      );
    }
  


export const getBulkUpsertProteinsApiV1ProteinsBulkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesProteinsBulkUpsertBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesProteinsBulkUpsertBody}, TContext> => {

const mutationKey = ['bulkUpsertProteinsApiV1ProteinsBulkPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>, {data: ProtcellarInterfaceRoutesProteinsBulkUpsertBody}> = (props) => {
          const {data} = props ?? {};

          return  bulkUpsertProteinsApiV1ProteinsBulkPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkUpsertProteinsApiV1ProteinsBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>>
    export type BulkUpsertProteinsApiV1ProteinsBulkPostMutationBody = ProtcellarInterfaceRoutesProteinsBulkUpsertBody
    export type BulkUpsertProteinsApiV1ProteinsBulkPostMutationError = HTTPValidationError

    /**
 * @summary Bulk Upsert Proteins
 */
export const useBulkUpsertProteinsApiV1ProteinsBulkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>, TError,{data: ProtcellarInterfaceRoutesProteinsBulkUpsertBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkUpsertProteinsApiV1ProteinsBulkPost>>,
        TError,
        {data: ProtcellarInterfaceRoutesProteinsBulkUpsertBody},
        TContext
      > => {

      const mutationOptions = getBulkUpsertProteinsApiV1ProteinsBulkPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Protein
 */
export const getProteinApiV1ProteinsAccessionGet = (
    accession: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/proteins/${accession}`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetProteinApiV1ProteinsAccessionGetQueryKey = (accession?: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams,) => {
    return [
    `/api/v1/proteins/${accession}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetProteinApiV1ProteinsAccessionGetQueryOptions = <TData = Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError = HTTPValidationError>(accession: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProteinApiV1ProteinsAccessionGetQueryKey(accession,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>> = ({ signal }) => getProteinApiV1ProteinsAccessionGet(accession,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(accession), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProteinApiV1ProteinsAccessionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>>
export type GetProteinApiV1ProteinsAccessionGetQueryError = HTTPValidationError


export function useGetProteinApiV1ProteinsAccessionGet<TData = Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError = HTTPValidationError>(
 accession: string,
    params: undefined |  GetProteinApiV1ProteinsAccessionGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>,
          TError,
          Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteinApiV1ProteinsAccessionGet<TData = Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError = HTTPValidationError>(
 accession: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>,
          TError,
          Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteinApiV1ProteinsAccessionGet<TData = Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError = HTTPValidationError>(
 accession: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Protein
 */

export function useGetProteinApiV1ProteinsAccessionGet<TData = Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError = HTTPValidationError>(
 accession: string,
    params?: GetProteinApiV1ProteinsAccessionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteinApiV1ProteinsAccessionGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProteinApiV1ProteinsAccessionGetQueryOptions(accession,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Protein
 */
export const updateProteinApiV1ProteinsAccessionPatch = (
    accession: string,
    updateProteinBody: UpdateProteinBody,
 ) => {
      
      
      return customInstance<ProteinResponse>(
      {url: `/api/v1/proteins/${accession}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProteinBody
    },
      );
    }
  


export const getUpdateProteinApiV1ProteinsAccessionPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>, TError,{accession: string;data: UpdateProteinBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>, TError,{accession: string;data: UpdateProteinBody}, TContext> => {

const mutationKey = ['updateProteinApiV1ProteinsAccessionPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>, {accession: string;data: UpdateProteinBody}> = (props) => {
          const {accession,data} = props ?? {};

          return  updateProteinApiV1ProteinsAccessionPatch(accession,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProteinApiV1ProteinsAccessionPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>>
    export type UpdateProteinApiV1ProteinsAccessionPatchMutationBody = UpdateProteinBody
    export type UpdateProteinApiV1ProteinsAccessionPatchMutationError = HTTPValidationError

    /**
 * @summary Update Protein
 */
export const useUpdateProteinApiV1ProteinsAccessionPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>, TError,{accession: string;data: UpdateProteinBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProteinApiV1ProteinsAccessionPatch>>,
        TError,
        {accession: string;data: UpdateProteinBody},
        TContext
      > => {

      const mutationOptions = getUpdateProteinApiV1ProteinsAccessionPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    