/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProteomeBody,
  HTTPValidationError,
  ListProteomesApiV1ProteomesGetParams,
  PaginatedResponseProteomeResponse,
  ProteomeResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Proteomes
 */
export const listProteomesApiV1ProteomesGet = (
    params?: ListProteomesApiV1ProteomesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseProteomeResponse>(
      {url: `/api/v1/proteomes`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListProteomesApiV1ProteomesGetQueryKey = (params?: ListProteomesApiV1ProteomesGetParams,) => {
    return [
    `/api/v1/proteomes`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProteomesApiV1ProteomesGetQueryOptions = <TData = Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError = HTTPValidationError>(params?: ListProteomesApiV1ProteomesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProteomesApiV1ProteomesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>> = ({ signal }) => listProteomesApiV1ProteomesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProteomesApiV1ProteomesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>>
export type ListProteomesApiV1ProteomesGetQueryError = HTTPValidationError


export function useListProteomesApiV1ProteomesGet<TData = Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListProteomesApiV1ProteomesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>,
          TError,
          Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProteomesApiV1ProteomesGet<TData = Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError = HTTPValidationError>(
 params?: ListProteomesApiV1ProteomesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>,
          TError,
          Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProteomesApiV1ProteomesGet<TData = Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError = HTTPValidationError>(
 params?: ListProteomesApiV1ProteomesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Proteomes
 */

export function useListProteomesApiV1ProteomesGet<TData = Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError = HTTPValidationError>(
 params?: ListProteomesApiV1ProteomesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProteomesApiV1ProteomesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProteomesApiV1ProteomesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Proteome
 */
export const createProteomeApiV1ProteomesPost = (
    createProteomeBody: CreateProteomeBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProteomeResponse>(
      {url: `/api/v1/proteomes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProteomeBody, signal
    },
      );
    }
  


export const getCreateProteomeApiV1ProteomesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>, TError,{data: CreateProteomeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>, TError,{data: CreateProteomeBody}, TContext> => {

const mutationKey = ['createProteomeApiV1ProteomesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>, {data: CreateProteomeBody}> = (props) => {
          const {data} = props ?? {};

          return  createProteomeApiV1ProteomesPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProteomeApiV1ProteomesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>>
    export type CreateProteomeApiV1ProteomesPostMutationBody = CreateProteomeBody
    export type CreateProteomeApiV1ProteomesPostMutationError = HTTPValidationError

    /**
 * @summary Create Proteome
 */
export const useCreateProteomeApiV1ProteomesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>, TError,{data: CreateProteomeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProteomeApiV1ProteomesPost>>,
        TError,
        {data: CreateProteomeBody},
        TContext
      > => {

      const mutationOptions = getCreateProteomeApiV1ProteomesPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Proteome
 */
export const getProteomeApiV1ProteomesProteomeIdGet = (
    proteomeId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ProteomeResponse>(
      {url: `/api/v1/proteomes/${proteomeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProteomeApiV1ProteomesProteomeIdGetQueryKey = (proteomeId?: string,) => {
    return [
    `/api/v1/proteomes/${proteomeId}`
    ] as const;
    }

    
export const getGetProteomeApiV1ProteomesProteomeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError = HTTPValidationError>(proteomeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProteomeApiV1ProteomesProteomeIdGetQueryKey(proteomeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>> = ({ signal }) => getProteomeApiV1ProteomesProteomeIdGet(proteomeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(proteomeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProteomeApiV1ProteomesProteomeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>>
export type GetProteomeApiV1ProteomesProteomeIdGetQueryError = HTTPValidationError


export function useGetProteomeApiV1ProteomesProteomeIdGet<TData = Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError = HTTPValidationError>(
 proteomeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteomeApiV1ProteomesProteomeIdGet<TData = Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError = HTTPValidationError>(
 proteomeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProteomeApiV1ProteomesProteomeIdGet<TData = Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError = HTTPValidationError>(
 proteomeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Proteome
 */

export function useGetProteomeApiV1ProteomesProteomeIdGet<TData = Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError = HTTPValidationError>(
 proteomeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProteomeApiV1ProteomesProteomeIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProteomeApiV1ProteomesProteomeIdGetQueryOptions(proteomeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




