"""organism provenance columns

Revision ID: 1c0c9700a15a
Revises: e47eea4f37c6
Create Date: 2026-06-18 11:53:23.210966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0c9700a15a'
down_revision: Union[str, None] = 'e47eea4f37c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisms', sa.Column('source_release', sa.String(length=64), nullable=True))
    op.add_column('organisms', sa.Column('source_record_id', sa.String(length=128), nullable=True))
    op.add_column('organisms', sa.Column('source_record_checksum', sa.String(length=64), nullable=True))
    op.add_column('organisms', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_organisms_source_record_id'), 'organisms', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisms_source_record_id'), table_name='organisms')
    op.drop_column('organisms', 'imported_at')
    op.drop_column('organisms', 'source_record_checksum')
    op.drop_column('organisms', 'source_record_id')
    op.drop_column('organisms', 'source_release')
    # ### end Alembic commands ###
