"""strain tables

Revision ID: 1e82e79b1191
Revises: 1c0c9700a15a
Create Date: 2026-06-18 12:26:51.089925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e82e79b1191'
down_revision: Union[str, None] = '1c0c9700a15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strains',
    sa.Column('species_organism_id', sa.Uuid(), nullable=False),
    sa.Column('strain_organism_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('isolate', sa.String(length=256), nullable=True),
    sa.Column('biosample_acc', sa.String(length=64), nullable=True),
    sa.Column('assembly_acc', sa.String(length=64), nullable=True),
    sa.Column('culture_collection', sa.String(length=128), nullable=True),
    sa.Column('host_organism_id', sa.Uuid(), nullable=True),
    sa.Column('strain_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_organism_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['species_organism_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['strain_organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strains_assembly_acc'), 'strains', ['assembly_acc'], unique=False)
    op.create_index(op.f('ix_strains_biosample_acc'), 'strains', ['biosample_acc'], unique=False)
    op.create_index(op.f('ix_strains_species_organism_id'), 'strains', ['species_organism_id'], unique=False)
    op.create_index(op.f('ix_strains_workspace_id'), 'strains', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strains_workspace_id'), table_name='strains')
    op.drop_index(op.f('ix_strains_species_organism_id'), table_name='strains')
    op.drop_index(op.f('ix_strains_biosample_acc'), table_name='strains')
    op.drop_index(op.f('ix_strains_assembly_acc'), table_name='strains')
    op.drop_table('strains')
    # ### end Alembic commands ###
