"""protein tables

Revision ID: 6d3ba0730540
Revises: bf02986f1c75
Create Date: 2026-06-18 22:13:22.105530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3ba0730540'
down_revision: Union[str, None] = 'bf02986f1c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proteins',
    sa.Column('primary_accession', sa.String(length=10), nullable=False),
    sa.Column('secondary_accessions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('entry_name', sa.String(length=32), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('protein_names', sa.JSON(), nullable=True),
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('strain_id', sa.Uuid(), nullable=True),
    sa.Column('gene_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('seq_length', sa.Integer(), nullable=False),
    sa.Column('seq_mass', sa.Integer(), nullable=True),
    sa.Column('seq_crc64', sa.String(length=16), nullable=True),
    sa.Column('protein_existence', sa.String(length=32), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('entry_version', sa.Integer(), nullable=True),
    sa.Column('sequence_version', sa.Integer(), nullable=True),
    sa.Column('cross_references', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_release', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('source_record_checksum', sa.String(length=64), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proteins_entry_name'), 'proteins', ['entry_name'], unique=False)
    op.create_index(op.f('ix_proteins_gene_id'), 'proteins', ['gene_id'], unique=False)
    op.create_index(op.f('ix_proteins_is_reviewed'), 'proteins', ['is_reviewed'], unique=False)
    op.create_index(op.f('ix_proteins_organism_id'), 'proteins', ['organism_id'], unique=False)
    op.create_index('ix_proteins_primary_accession', 'proteins', ['primary_accession'], unique=True)
    op.create_index('ix_proteins_secondary_accessions', 'proteins', ['secondary_accessions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_proteins_seq_length'), 'proteins', ['seq_length'], unique=False)
    op.create_index(op.f('ix_proteins_source'), 'proteins', ['source'], unique=False)
    op.create_index(op.f('ix_proteins_source_record_id'), 'proteins', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_proteins_strain_id'), 'proteins', ['strain_id'], unique=False)
    op.create_index(op.f('ix_proteins_workspace_id'), 'proteins', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proteins_workspace_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_strain_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_source_record_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_source'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_seq_length'), table_name='proteins')
    op.drop_index('ix_proteins_secondary_accessions', table_name='proteins', postgresql_using='gin')
    op.drop_index('ix_proteins_primary_accession', table_name='proteins')
    op.drop_index(op.f('ix_proteins_organism_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_is_reviewed'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_gene_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_entry_name'), table_name='proteins')
    op.drop_table('proteins')
    # ### end Alembic commands ###
