"""target tables

Revision ID: 6d6ec789aaae
Revises: 6d3ba0730540
Create Date: 2026-06-18 23:10:16.986139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6ec789aaae'
down_revision: Union[str, None] = '6d3ba0730540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('pref_name', sa.String(length=512), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('organism_id', sa.Uuid(), nullable=True),
    sa.Column('chembl_id', sa.String(length=32), nullable=True),
    sa.Column('pharmacological_class', sa.String(length=256), nullable=True),
    sa.Column('cross_references', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_chembl_id'), 'targets', ['chembl_id'], unique=False)
    op.create_index(op.f('ix_targets_organism_id'), 'targets', ['organism_id'], unique=False)
    op.create_index(op.f('ix_targets_pref_name'), 'targets', ['pref_name'], unique=False)
    op.create_index(op.f('ix_targets_target_type'), 'targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_targets_workspace_id'), 'targets', ['workspace_id'], unique=False)
    op.create_table('target_components',
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('protein_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_components_protein_id'), 'target_components', ['protein_id'], unique=False)
    op.create_index(op.f('ix_target_components_target_id'), 'target_components', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_components_target_id'), table_name='target_components')
    op.drop_index(op.f('ix_target_components_protein_id'), table_name='target_components')
    op.drop_table('target_components')
    op.drop_index(op.f('ix_targets_workspace_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_target_type'), table_name='targets')
    op.drop_index(op.f('ix_targets_pref_name'), table_name='targets')
    op.drop_index(op.f('ix_targets_organism_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_chembl_id'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
