"""proteome tables

Revision ID: 79dd72e6ee46
Revises: 1e82e79b1191
Create Date: 2026-06-18 12:40:04.258491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dd72e6ee46'
down_revision: Union[str, None] = '1e82e79b1191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proteomes',
    sa.Column('uniprot_proteome_id', sa.String(length=16), nullable=False),
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('strain_id', sa.Uuid(), nullable=True),
    sa.Column('proteome_type', sa.String(length=32), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('assembly_acc', sa.String(length=64), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_release', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('source_record_checksum', sa.String(length=64), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proteomes_organism_id'), 'proteomes', ['organism_id'], unique=False)
    op.create_index(op.f('ix_proteomes_source'), 'proteomes', ['source'], unique=False)
    op.create_index(op.f('ix_proteomes_source_record_id'), 'proteomes', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_proteomes_strain_id'), 'proteomes', ['strain_id'], unique=False)
    op.create_index('ix_proteomes_uniprot_proteome_id', 'proteomes', ['uniprot_proteome_id'], unique=True)
    op.create_index(op.f('ix_proteomes_workspace_id'), 'proteomes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proteomes_workspace_id'), table_name='proteomes')
    op.drop_index('ix_proteomes_uniprot_proteome_id', table_name='proteomes')
    op.drop_index(op.f('ix_proteomes_strain_id'), table_name='proteomes')
    op.drop_index(op.f('ix_proteomes_source_record_id'), table_name='proteomes')
    op.drop_index(op.f('ix_proteomes_source'), table_name='proteomes')
    op.drop_index(op.f('ix_proteomes_organism_id'), table_name='proteomes')
    op.drop_table('proteomes')
    # ### end Alembic commands ###
