"""audit tables

Revision ID: a9067fb18141
Revises: 
Create Date: 2026-06-18 10:54:58.999942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9067fb18141'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='completed', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['correlation_id'], ['audit_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_operations_correlation_id', 'audit_operations', ['correlation_id'], unique=False)
    op.create_index('ix_audit_operations_entity', 'audit_operations', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_operations_user_id', 'audit_operations', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_operations_workspace_id'), 'audit_operations', ['workspace_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['audit_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entries_entity', 'audit_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_operation_id'), 'audit_entries', ['operation_id'], unique=False)
    op.create_table('electronic_signatures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['audit_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electronic_signatures')
    op.drop_index(op.f('ix_audit_entries_operation_id'), table_name='audit_entries')
    op.drop_index('ix_audit_entries_entity', table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_audit_operations_workspace_id'), table_name='audit_operations')
    op.drop_index('ix_audit_operations_user_id', table_name='audit_operations')
    op.drop_index('ix_audit_operations_entity', table_name='audit_operations')
    op.drop_index('ix_audit_operations_correlation_id', table_name='audit_operations')
    op.drop_table('audit_operations')
    # ### end Alembic commands ###
