"""gene tables

Revision ID: bf02986f1c75
Revises: 79dd72e6ee46
Create Date: 2026-06-18 22:01:35.626551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf02986f1c75'
down_revision: Union[str, None] = '79dd72e6ee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genes',
    sa.Column('primary_name', sa.String(length=128), nullable=False),
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ncbi_gene_id', sa.String(length=32), nullable=True),
    sa.Column('ensembl_gene_id', sa.String(length=32), nullable=True),
    sa.Column('hgnc_id', sa.String(length=32), nullable=True),
    sa.Column('cross_references', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_release', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('source_record_checksum', sa.String(length=64), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_ensembl_gene_id'), 'genes', ['ensembl_gene_id'], unique=False)
    op.create_index(op.f('ix_genes_ncbi_gene_id'), 'genes', ['ncbi_gene_id'], unique=False)
    op.create_index(op.f('ix_genes_organism_id'), 'genes', ['organism_id'], unique=False)
    op.create_index(op.f('ix_genes_primary_name'), 'genes', ['primary_name'], unique=False)
    op.create_index(op.f('ix_genes_source'), 'genes', ['source'], unique=False)
    op.create_index(op.f('ix_genes_source_record_id'), 'genes', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_genes_workspace_id'), 'genes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genes_workspace_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_source_record_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_source'), table_name='genes')
    op.drop_index(op.f('ix_genes_primary_name'), table_name='genes')
    op.drop_index(op.f('ix_genes_organism_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_ncbi_gene_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_ensembl_gene_id'), table_name='genes')
    op.drop_table('genes')
    # ### end Alembic commands ###
