"""extension field defs

Revision ID: e3c9a1f7b508
Revises: d2b5f9c8e314
Create Date: 2026-08-09 11:25:05.933540

A workspace's declaration of one extra field on one target-biology record kind.
`name` is the key inside that kind's `extensions` JSONB bag; it is immutable in
the domain (renaming it would orphan every stored value) but nothing at the
schema level enforces that — it is a plain column, guarded by the aggregate.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c9a1f7b508'
down_revision: Union[str, None] = 'd2b5f9c8e314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_field_defs',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('show_in_table', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_field_defs_workspace_id'), 'extension_field_defs', ['workspace_id'], unique=False)
    op.create_index('ix_extension_field_defs_ws_kind', 'extension_field_defs', ['workspace_id', 'kind'], unique=False)
    op.create_index('uq_extension_field_defs_ws_kind_name', 'extension_field_defs', ['workspace_id', 'kind', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_extension_field_defs_ws_kind_name', table_name='extension_field_defs')
    op.drop_index('ix_extension_field_defs_ws_kind', table_name='extension_field_defs')
    op.drop_index(op.f('ix_extension_field_defs_workspace_id'), table_name='extension_field_defs')
    op.drop_table('extension_field_defs')
    # ### end Alembic commands ###
