"""organism tables

Revision ID: e47eea4f37c6
Revises: 7dba9d184aec
Create Date: 2026-06-18 11:49:15.998260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47eea4f37c6'
down_revision: Union[str, None] = '7dba9d184aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisms',
    sa.Column('ncbi_tax_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.String(length=32), nullable=False),
    sa.Column('scientific_name', sa.String(length=512), nullable=False),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('is_merged', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisms_is_deleted'), 'organisms', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organisms_ncbi_tax_id'), 'organisms', ['ncbi_tax_id'], unique=True)
    op.create_index(op.f('ix_organisms_parent_id'), 'organisms', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organisms_rank'), 'organisms', ['rank'], unique=False)
    op.create_index(op.f('ix_organisms_scientific_name'), 'organisms', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_organisms_workspace_id'), 'organisms', ['workspace_id'], unique=False)
    op.create_table('organism_names',
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_class', sa.String(length=32), nullable=False),
    sa.Column('unique_name', sa.String(length=512), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organism_id', 'name_class', 'name', name='uq_orgname')
    )
    op.create_index(op.f('ix_organism_names_name'), 'organism_names', ['name'], unique=False)
    op.create_index(op.f('ix_organism_names_organism_id'), 'organism_names', ['organism_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organism_names_organism_id'), table_name='organism_names')
    op.drop_index(op.f('ix_organism_names_name'), table_name='organism_names')
    op.drop_table('organism_names')
    op.drop_index(op.f('ix_organisms_workspace_id'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_scientific_name'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_rank'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_parent_id'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_ncbi_tax_id'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_is_deleted'), table_name='organisms')
    op.drop_table('organisms')
    # ### end Alembic commands ###
