/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ItemResultResponse } from './itemResultResponse';
import type { BulkSummaryResponse } from './bulkSummaryResponse';

export interface BulkUpsertResponse {
  results: ItemResultResponse[];
  summary: BulkSummaryResponse;
}
