/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { BulkGeneRecordBodyNcbiGeneId } from './bulkGeneRecordBodyNcbiGeneId';
import type { BulkGeneRecordBodyEnsemblGeneId } from './bulkGeneRecordBodyEnsemblGeneId';
import type { BulkCrossReferenceBody } from './bulkCrossReferenceBody';

export interface BulkGeneRecordBody {
  primary_name: string;
  organism_id: string;
  source: string;
  source_release: string;
  source_record_id: string;
  source_record_checksum: string;
  synonyms?: string[];
  ncbi_gene_id?: BulkGeneRecordBodyNcbiGeneId;
  ensembl_gene_id?: BulkGeneRecordBodyEnsemblGeneId;
  cross_references?: BulkCrossReferenceBody[];
}
