/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CitationResponseCitationType } from './citationResponseCitationType';
import type { CitationResponseTitle } from './citationResponseTitle';
import type { CitationResponseJournal } from './citationResponseJournal';
import type { CitationResponseAuthors } from './citationResponseAuthors';
import type { CitationResponsePublicationDate } from './citationResponsePublicationDate';
import type { CitationResponsePubmedId } from './citationResponsePubmedId';
import type { CitationResponseDoi } from './citationResponseDoi';
import type { CitationResponseReferenceNumber } from './citationResponseReferenceNumber';
import type { CitationResponsePositions } from './citationResponsePositions';
import type { CitationResponseReferenceComments } from './citationResponseReferenceComments';

export interface CitationResponse {
  citation_type?: CitationResponseCitationType;
  title?: CitationResponseTitle;
  journal?: CitationResponseJournal;
  authors?: CitationResponseAuthors;
  publication_date?: CitationResponsePublicationDate;
  pubmed_id?: CitationResponsePubmedId;
  doi?: CitationResponseDoi;
  reference_number?: CitationResponseReferenceNumber;
  positions?: CitationResponsePositions;
  reference_comments?: CitationResponseReferenceComments;
}
