/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CitationBodyCitationType } from './citationBodyCitationType';
import type { CitationBodyTitle } from './citationBodyTitle';
import type { CitationBodyJournal } from './citationBodyJournal';
import type { CitationBodyAuthors } from './citationBodyAuthors';
import type { CitationBodyPublicationDate } from './citationBodyPublicationDate';
import type { CitationBodyPubmedId } from './citationBodyPubmedId';
import type { CitationBodyDoi } from './citationBodyDoi';
import type { CitationBodyReferenceNumber } from './citationBodyReferenceNumber';
import type { CitationBodyPositions } from './citationBodyPositions';
import type { CitationBodyReferenceComments } from './citationBodyReferenceComments';

export interface CitationBody {
  citation_type?: CitationBodyCitationType;
  title?: CitationBodyTitle;
  journal?: CitationBodyJournal;
  authors?: CitationBodyAuthors;
  publication_date?: CitationBodyPublicationDate;
  pubmed_id?: CitationBodyPubmedId;
  doi?: CitationBodyDoi;
  reference_number?: CitationBodyReferenceNumber;
  positions?: CitationBodyPositions;
  reference_comments?: CitationBodyReferenceComments;
}
