/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CommentBodyText } from './commentBodyText';
import type { CommentBodyPayload } from './commentBodyPayload';
import type { CommentBodyEvidence } from './commentBodyEvidence';

export interface CommentBody {
  comment_type: string;
  text?: CommentBodyText;
  payload?: CommentBodyPayload;
  evidence?: CommentBodyEvidence;
}
