/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CompoundRefBodyName } from './compoundRefBodyName';

/**
 * Inbound reference to a compound held in a chemistry catalog.

This service does not resolve the id — it stores the caller's pair verbatim, the
same self-contained reference `CompoundRef` already models. `name` is a
denormalized label for display; `compound_id` is the identity.
 */
export interface CompoundRefBody {
  compound_id: string;
  name?: CompoundRefBodyName;
}
