/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CompoundRefResponseName } from './compoundRefResponseName';

export interface CompoundRefResponse {
  compound_id: string;
  name?: CompoundRefResponseName;
}
