/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ComponentRelationship } from './componentRelationship';

export interface ComponentResponse {
  id: string;
  protein_id: string;
  relationship: ComponentRelationship;
}
