/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateGeneBodyNcbiGeneId } from './createGeneBodyNcbiGeneId';
import type { CreateGeneBodyEnsemblGeneId } from './createGeneBodyEnsemblGeneId';
import type { CreateGeneBodyHgncId } from './createGeneBodyHgncId';

export interface CreateGeneBody {
  primary_name: string;
  organism_id: string;
  synonyms?: string[];
  ncbi_gene_id?: CreateGeneBodyNcbiGeneId;
  ensembl_gene_id?: CreateGeneBodyEnsemblGeneId;
  hgnc_id?: CreateGeneBodyHgncId;
}
