/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { RecordKind } from './recordKind';
import type { ExtensionFieldType } from './extensionFieldType';
import type { CreateFieldDefBodyOptions } from './createFieldDefBodyOptions';

export interface CreateFieldDefBody {
  kind: RecordKind;
  name: string;
  label: string;
  field_type: ExtensionFieldType;
  options?: CreateFieldDefBodyOptions;
  position: number;
  show_in_table: boolean;
}
