/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateOrganismBodyNcbiTaxId } from './createOrganismBodyNcbiTaxId';
import type { OrganismSource } from './organismSource';
import type { CreateOrganismBodyDivision } from './createOrganismBodyDivision';
import type { CreateOrganismBodySourceVersion } from './createOrganismBodySourceVersion';

export interface CreateOrganismBody {
  ncbi_tax_id?: CreateOrganismBodyNcbiTaxId;
  rank: string;
  scientific_name: string;
  source?: OrganismSource;
  division?: CreateOrganismBodyDivision;
  source_version?: CreateOrganismBodySourceVersion;
}
