/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateStrainBodyStrainOrganismId } from './createStrainBodyStrainOrganismId';
import type { CreateStrainBodyIsolate } from './createStrainBodyIsolate';
import type { CreateStrainBodyBiosampleAcc } from './createStrainBodyBiosampleAcc';
import type { CreateStrainBodyAssemblyAcc } from './createStrainBodyAssemblyAcc';
import type { CreateStrainBodyCultureCollection } from './createStrainBodyCultureCollection';
import type { CreateStrainBodyHostOrganismId } from './createStrainBodyHostOrganismId';
import type { CreateStrainBodyMetadata } from './createStrainBodyMetadata';

export interface CreateStrainBody {
  species_organism_id: string;
  name: string;
  strain_organism_id?: CreateStrainBodyStrainOrganismId;
  isolate?: CreateStrainBodyIsolate;
  biosample_acc?: CreateStrainBodyBiosampleAcc;
  assembly_acc?: CreateStrainBodyAssemblyAcc;
  culture_collection?: CreateStrainBodyCultureCollection;
  host_organism_id?: CreateStrainBodyHostOrganismId;
  metadata?: CreateStrainBodyMetadata;
}
