/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteomeType } from './proteomeType';
import type { CreateProteomeBodyStrainId } from './createProteomeBodyStrainId';
import type { CreateProteomeBodyAssemblyAcc } from './createProteomeBodyAssemblyAcc';
import type { CreateProteomeBodySourceVersion } from './createProteomeBodySourceVersion';

export interface CreateProteomeBody {
  uniprot_proteome_id: string;
  organism_id: string;
  proteome_type: ProteomeType;
  is_reference: boolean;
  strain_id?: CreateProteomeBodyStrainId;
  assembly_acc?: CreateProteomeBodyAssemblyAcc;
  source_version?: CreateProteomeBodySourceVersion;
}
