/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProteinBodyEntryName } from './createProteinBodyEntryName';
import type { CreateProteinBodyProteinNames } from './createProteinBodyProteinNames';
import type { CreateProteinBodyStrainId } from './createProteinBodyStrainId';
import type { CreateProteinBodyGeneId } from './createProteinBodyGeneId';
import type { CreateProteinBodySeqMass } from './createProteinBodySeqMass';
import type { CreateProteinBodySeqCrc64 } from './createProteinBodySeqCrc64';
import type { CreateProteinBodyProteinExistence } from './createProteinBodyProteinExistence';
import type { CreateProteinBodyEntryVersion } from './createProteinBodyEntryVersion';
import type { CreateProteinBodySequenceVersion } from './createProteinBodySequenceVersion';
import type { CrossReferenceBody } from './crossReferenceBody';

export interface CreateProteinBody {
  primary_accession: string;
  organism_id: string;
  sequence: string;
  is_reviewed?: boolean;
  secondary_accessions?: string[];
  entry_name?: CreateProteinBodyEntryName;
  protein_names?: CreateProteinBodyProteinNames;
  strain_id?: CreateProteinBodyStrainId;
  gene_id?: CreateProteinBodyGeneId;
  seq_mass?: CreateProteinBodySeqMass;
  seq_crc64?: CreateProteinBodySeqCrc64;
  protein_existence?: CreateProteinBodyProteinExistence;
  keywords?: string[];
  entry_version?: CreateProteinBodyEntryVersion;
  sequence_version?: CreateProteinBodySequenceVersion;
  cross_references?: CrossReferenceBody[];
}
