/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { TargetType } from './targetType';
import type { ComponentBody } from './componentBody';
import type { CreateTargetBodyOrganismId } from './createTargetBodyOrganismId';
import type { CreateTargetBodyChemblId } from './createTargetBodyChemblId';
import type { CreateTargetBodyPharmacologicalClass } from './createTargetBodyPharmacologicalClass';
import type { CrossReferenceBody } from './crossReferenceBody';

export interface CreateTargetBody {
  pref_name: string;
  target_type: TargetType;
  components?: ComponentBody[];
  organism_id?: CreateTargetBodyOrganismId;
  chembl_id?: CreateTargetBodyChemblId;
  pharmacological_class?: CreateTargetBodyPharmacologicalClass;
  cross_references?: CrossReferenceBody[];
}
