/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationType } from './organizationType';
import type { CreateOrganizationBodyContactName } from './createOrganizationBodyContactName';
import type { CreateOrganizationBodyContactEmail } from './createOrganizationBodyContactEmail';
import type { CreateOrganizationBodyNotes } from './createOrganizationBodyNotes';

export interface CreateOrganizationBody {
  name: string;
  org_type: OrganizationType;
  contact_name?: CreateOrganizationBodyContactName;
  contact_email?: CreateOrganizationBodyContactEmail;
  notes?: CreateOrganizationBodyNotes;
}
