/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProvenanceBody } from './provenanceBody';
import type { CrispriStrainWriteBodyExtensions } from './crispriStrainWriteBodyExtensions';

export interface CrispriStrainWriteBody {
  name: string;
  provenance: ProvenanceBody;
  extensions?: CrispriStrainWriteBodyExtensions;
}
