/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CrispriStrainPatchBodyName } from './crispriStrainPatchBodyName';
import type { CrispriStrainPatchBodyProvenance } from './crispriStrainPatchBodyProvenance';
import type { CrispriStrainPatchBodyExtensions } from './crispriStrainPatchBodyExtensions';
import type { CrispriStrainPatchBodyVersion } from './crispriStrainPatchBodyVersion';

export interface CrispriStrainPatchBody {
  name?: CrispriStrainPatchBodyName;
  provenance?: CrispriStrainPatchBodyProvenance;
  extensions?: CrispriStrainPatchBodyExtensions;
  version?: CrispriStrainPatchBodyVersion;
}
