/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProvenanceResponse } from './provenanceResponse';
import type { CrispriStrainResponseExtensions } from './crispriStrainResponseExtensions';

export interface CrispriStrainResponse {
  id: string;
  name: string;
  target_gene_id: string;
  provenance: ProvenanceResponse;
  extensions: CrispriStrainResponseExtensions;
}
