/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { CrossReferenceBodyProperties } from './crossReferenceBodyProperties';
import type { CrossReferenceBodyEvidence } from './crossReferenceBodyEvidence';

export interface CrossReferenceBody {
  database: string;
  accession: string;
  properties?: CrossReferenceBodyProperties;
  evidence?: CrossReferenceBodyEvidence;
}
