/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EntityTagResponseValue } from './entityTagResponseValue';

/**
 * A tag on an entity, plus the assignment provenance (who/when tagged it).
 */
export interface EntityTagResponse {
  id: string;
  workspace_id: string;
  key: string;
  value: EntityTagResponseValue;
  created_by: string;
  created_at: string;
  assigned_by: string;
  assigned_at: string;
}
