/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EssentialityResponseCondition } from './essentialityResponseCondition';
import type { EssentialityResponseMethod } from './essentialityResponseMethod';
import type { EssentialityResponseConfidence } from './essentialityResponseConfidence';
import type { ProvenanceResponse } from './provenanceResponse';
import type { EssentialityResponseExtensions } from './essentialityResponseExtensions';

export interface EssentialityResponse {
  id: string;
  gene_id: string;
  classification: string;
  condition?: EssentialityResponseCondition;
  method?: EssentialityResponseMethod;
  confidence?: EssentialityResponseConfidence;
  provenance: ProvenanceResponse;
  extensions: EssentialityResponseExtensions;
}
