/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type EssentialityClass = typeof EssentialityClass[keyof typeof EssentialityClass];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EssentialityClass = {
  essential: 'essential',
  growth_defect: 'growth_defect',
  non_essential: 'non_essential',
  growth_advantage: 'growth_advantage',
  uncertain: 'uncertain',
} as const;
