/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EssentialityClass } from './essentialityClass';
import type { EssentialityWriteBodyCondition } from './essentialityWriteBodyCondition';
import type { EssentialityWriteBodyMethod } from './essentialityWriteBodyMethod';
import type { EssentialityWriteBodyConfidence } from './essentialityWriteBodyConfidence';
import type { ProvenanceBody } from './provenanceBody';
import type { EssentialityWriteBodyExtensions } from './essentialityWriteBodyExtensions';

export interface EssentialityWriteBody {
  classification: EssentialityClass;
  condition?: EssentialityWriteBodyCondition;
  method?: EssentialityWriteBodyMethod;
  confidence?: EssentialityWriteBodyConfidence;
  provenance: ProvenanceBody;
  extensions?: EssentialityWriteBodyExtensions;
}
