/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EssentialityWriteBodyExtensionsAnyOf } from './essentialityWriteBodyExtensionsAnyOf';

export type EssentialityWriteBodyExtensions = EssentialityWriteBodyExtensionsAnyOf | null;
