/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EssentialityPatchBodyClassification } from './essentialityPatchBodyClassification';
import type { EssentialityPatchBodyCondition } from './essentialityPatchBodyCondition';
import type { EssentialityPatchBodyMethod } from './essentialityPatchBodyMethod';
import type { EssentialityPatchBodyConfidence } from './essentialityPatchBodyConfidence';
import type { EssentialityPatchBodyProvenance } from './essentialityPatchBodyProvenance';
import type { EssentialityPatchBodyVersion } from './essentialityPatchBodyVersion';

export interface EssentialityPatchBody {
  classification?: EssentialityPatchBodyClassification;
  condition?: EssentialityPatchBodyCondition;
  method?: EssentialityPatchBodyMethod;
  confidence?: EssentialityPatchBodyConfidence;
  provenance?: EssentialityPatchBodyProvenance;
  version?: EssentialityPatchBodyVersion;
}
