/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { FeatureBodyStart } from './featureBodyStart';
import type { FeatureBodyEnd } from './featureBodyEnd';
import type { FeatureBodyStartModifier } from './featureBodyStartModifier';
import type { FeatureBodyEndModifier } from './featureBodyEndModifier';
import type { FeatureBodyDescription } from './featureBodyDescription';
import type { FeatureBodyFeatureId } from './featureBodyFeatureId';
import type { FeatureBodyLigand } from './featureBodyLigand';
import type { FeatureBodyAlternativeSequence } from './featureBodyAlternativeSequence';
import type { FeatureBodyEvidence } from './featureBodyEvidence';

export interface FeatureBody {
  feature_type: string;
  start?: FeatureBodyStart;
  end?: FeatureBodyEnd;
  start_modifier?: FeatureBodyStartModifier;
  end_modifier?: FeatureBodyEndModifier;
  description?: FeatureBodyDescription;
  feature_id?: FeatureBodyFeatureId;
  ligand?: FeatureBodyLigand;
  alternative_sequence?: FeatureBodyAlternativeSequence;
  evidence?: FeatureBodyEvidence;
}
