/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * How a provenance-stamped value was produced — orthogonal to source_type.

source_type answers *publication status* (published/preprint/…); this answers
*how the value came to be*. An AI can extract a value from a published paper,
so both axes must coexist.
 */
export type GenerationMethod = typeof GenerationMethod[keyof typeof GenerationMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenerationMethod = {
  manual: 'manual',
  imported: 'imported',
  ai_extracted: 'ai_extracted',
  ai_predicted: 'ai_predicted',
  computed: 'computed',
} as const;
