/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * The drug-discovery question a gene annotation speaks to.

Universal across diseases; only the datasets that fill each axis differ.
 */
export type GeneAnnotationAxis = typeof GeneAnnotationAxis[keyof typeof GeneAnnotationAxis];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeneAnnotationAxis = {
  vulnerability: 'vulnerability',
  selectivity: 'selectivity',
  robustness: 'robustness',
  context: 'context',
  expression: 'expression',
} as const;
