/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneAnnotationAxis } from './geneAnnotationAxis';
import type { GeneAnnotationBodyDataset } from './geneAnnotationBodyDataset';
import type { GeneAnnotationBodyCondition } from './geneAnnotationBodyCondition';
import type { GeneAnnotationBodyEvidence } from './geneAnnotationBodyEvidence';
import type { GeneAnnotationBodySource } from './geneAnnotationBodySource';
import type { GeneAnnotationBodySourceUrl } from './geneAnnotationBodySourceUrl';

/**
 * Inbound axis-typed annotation (mirrors GeneAnnotationResponse minus computed fields).
 */
export interface GeneAnnotationBody {
  axis: GeneAnnotationAxis;
  key: string;
  value: string;
  value_type?: string;
  dataset?: GeneAnnotationBodyDataset;
  condition?: GeneAnnotationBodyCondition;
  evidence?: GeneAnnotationBodyEvidence;
  source?: GeneAnnotationBodySource;
  source_url?: GeneAnnotationBodySourceUrl;
}
