/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { EssentialityResponse } from './essentialityResponse';
import type { VulnerabilityResponse } from './vulnerabilityResponse';
import type { HypomorphResponse } from './hypomorphResponse';
import type { CrispriStrainResponse } from './crispriStrainResponse';
import type { ResistanceMutationResponse } from './resistanceMutationResponse';

export interface GeneTargetBiologyResponse {
  essentiality: EssentialityResponse[];
  vulnerability: VulnerabilityResponse[];
  hypomorph: HypomorphResponse[];
  crispri_strain: CrispriStrainResponse[];
  resistance_mutation: ResistanceMutationResponse[];
}
