/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneResponseNcbiGeneId } from './geneResponseNcbiGeneId';
import type { GeneResponseNcbiGeneUrl } from './geneResponseNcbiGeneUrl';
import type { GeneResponseEnsemblGeneId } from './geneResponseEnsemblGeneId';
import type { GeneResponseEnsemblUrl } from './geneResponseEnsemblUrl';
import type { GeneResponseHgncId } from './geneResponseHgncId';
import type { CrossReferenceResponse } from './crossReferenceResponse';

export interface GeneResponse {
  id: string;
  primary_name: string;
  organism_id: string;
  synonyms: string[];
  ncbi_gene_id?: GeneResponseNcbiGeneId;
  ncbi_gene_url?: GeneResponseNcbiGeneUrl;
  ensembl_gene_id?: GeneResponseEnsemblGeneId;
  ensembl_url?: GeneResponseEnsemblUrl;
  hgnc_id?: GeneResponseHgncId;
  cross_references: CrossReferenceResponse[];
  version: number;
}
