/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneItemResultResponse } from './geneItemResultResponse';
import type { GeneBulkSummaryResponse } from './geneBulkSummaryResponse';

export interface GeneBulkUpsertResponse {
  results: GeneItemResultResponse[];
  summary: GeneBulkSummaryResponse;
}
