/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lightweight gene fields embedded in the protein list for at-a-glance display.
 */
export interface GeneSummaryResponse {
  id: string;
  primary_name: string;
  synonyms: string[];
}
