/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneItemResultResponseId } from './geneItemResultResponseId';
import type { GeneItemResultResponseError } from './geneItemResultResponseError';

export interface GeneItemResultResponse {
  index: number;
  status: string;
  id?: GeneItemResultResponseId;
  error?: GeneItemResultResponseError;
}
