/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneNeighborSummaryGenomicStart } from './geneNeighborSummaryGenomicStart';
import type { GeneNeighborSummaryGenomicEnd } from './geneNeighborSummaryGenomicEnd';
import type { GeneNeighborSummaryGenomicStrand } from './geneNeighborSummaryGenomicStrand';
import type { GeneNeighborSummaryEssentiality } from './geneNeighborSummaryEssentiality';

export interface GeneNeighborSummary {
  id: string;
  primary_name: string;
  genomic_start?: GeneNeighborSummaryGenomicStart;
  genomic_end?: GeneNeighborSummaryGenomicEnd;
  genomic_strand?: GeneNeighborSummaryGenomicStrand;
  essentiality?: GeneNeighborSummaryEssentiality;
}
