/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneAnnotationResponseDataset } from './geneAnnotationResponseDataset';
import type { GeneAnnotationResponseCondition } from './geneAnnotationResponseCondition';
import type { GeneAnnotationResponseEvidence } from './geneAnnotationResponseEvidence';
import type { GeneAnnotationResponseSource } from './geneAnnotationResponseSource';
import type { GeneAnnotationResponseSourceUrl } from './geneAnnotationResponseSourceUrl';

export interface GeneAnnotationResponse {
  axis: string;
  key: string;
  value: string;
  value_type: string;
  dataset?: GeneAnnotationResponseDataset;
  condition?: GeneAnnotationResponseCondition;
  evidence?: GeneAnnotationResponseEvidence;
  source?: GeneAnnotationResponseSource;
  source_url?: GeneAnnotationResponseSourceUrl;
}
