/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export interface GeneBulkSummaryResponse {
  created: number;
  updated: number;
  skipped: number;
  failed: number;
}
