/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneResponseStrainId } from './geneResponseStrainId';
import type { GeneResponseNcbiGeneId } from './geneResponseNcbiGeneId';
import type { GeneResponseNcbiGeneUrl } from './geneResponseNcbiGeneUrl';
import type { GeneResponseEnsemblGeneId } from './geneResponseEnsemblGeneId';
import type { GeneResponseEnsemblUrl } from './geneResponseEnsemblUrl';
import type { GeneResponseHgncId } from './geneResponseHgncId';
import type { CrossReferenceResponse } from './crossReferenceResponse';
import type { GeneResponseGenomicAccession } from './geneResponseGenomicAccession';
import type { GeneResponseGenomicStart } from './geneResponseGenomicStart';
import type { GeneResponseGenomicEnd } from './geneResponseGenomicEnd';
import type { GeneResponseGenomicStrand } from './geneResponseGenomicStrand';
import type { GeneResponseAssembly } from './geneResponseAssembly';
import type { GeneResponseLengthBp } from './geneResponseLengthBp';
import type { GeneAnnotationResponse } from './geneAnnotationResponse';

export interface GeneResponse {
  id: string;
  primary_name: string;
  organism_id: string;
  strain_id?: GeneResponseStrainId;
  synonyms: string[];
  ordered_locus_names: string[];
  orf_names: string[];
  display_label: string;
  ncbi_gene_id?: GeneResponseNcbiGeneId;
  ncbi_gene_url?: GeneResponseNcbiGeneUrl;
  ensembl_gene_id?: GeneResponseEnsemblGeneId;
  ensembl_url?: GeneResponseEnsemblUrl;
  hgnc_id?: GeneResponseHgncId;
  cross_references: CrossReferenceResponse[];
  genomic_accession?: GeneResponseGenomicAccession;
  genomic_start?: GeneResponseGenomicStart;
  genomic_end?: GeneResponseGenomicEnd;
  genomic_strand?: GeneResponseGenomicStrand;
  assembly?: GeneResponseAssembly;
  length_bp?: GeneResponseLengthBp;
  annotations: GeneAnnotationResponse[];
  version: number;
}
