/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { HypomorphResponseGrowthDefectSeverity } from './hypomorphResponseGrowthDefectSeverity';
import type { HypomorphResponseKnockdownStrainId } from './hypomorphResponseKnockdownStrainId';
import type { HypomorphResponseCondition } from './hypomorphResponseCondition';
import type { HypomorphResponseMethod } from './hypomorphResponseMethod';
import type { ProvenanceResponse } from './provenanceResponse';
import type { HypomorphResponseExtensions } from './hypomorphResponseExtensions';

export interface HypomorphResponse {
  id: string;
  gene_id: string;
  growth_defect: boolean;
  growth_defect_severity?: HypomorphResponseGrowthDefectSeverity;
  knockdown_strain_id?: HypomorphResponseKnockdownStrainId;
  condition?: HypomorphResponseCondition;
  method?: HypomorphResponseMethod;
  provenance: ProvenanceResponse;
  extensions: HypomorphResponseExtensions;
}
