/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { HypomorphWriteBodyGrowthDefectSeverity } from './hypomorphWriteBodyGrowthDefectSeverity';
import type { HypomorphWriteBodyCondition } from './hypomorphWriteBodyCondition';
import type { HypomorphWriteBodyMethod } from './hypomorphWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';

export interface HypomorphWriteBody {
  growth_defect: boolean;
  growth_defect_severity?: HypomorphWriteBodyGrowthDefectSeverity;
  condition?: HypomorphWriteBodyCondition;
  method?: HypomorphWriteBodyMethod;
  provenance: ProvenanceBody;
}
