/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { HypomorphWriteBodyGrowthDefect } from './hypomorphWriteBodyGrowthDefect';
import type { HypomorphWriteBodyGrowthDefectSeverity } from './hypomorphWriteBodyGrowthDefectSeverity';
import type { HypomorphWriteBodyKnockdownStrainId } from './hypomorphWriteBodyKnockdownStrainId';
import type { HypomorphWriteBodyCondition } from './hypomorphWriteBodyCondition';
import type { HypomorphWriteBodyMethod } from './hypomorphWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';
import type { HypomorphWriteBodyExtensions } from './hypomorphWriteBodyExtensions';

export interface HypomorphWriteBody {
  growth_defect?: HypomorphWriteBodyGrowthDefect;
  growth_defect_severity?: HypomorphWriteBodyGrowthDefectSeverity;
  knockdown_strain_id?: HypomorphWriteBodyKnockdownStrainId;
  condition?: HypomorphWriteBodyCondition;
  method?: HypomorphWriteBodyMethod;
  provenance: ProvenanceBody;
  extensions?: HypomorphWriteBodyExtensions;
}
