/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { HypomorphPatchBodyGrowthDefect } from './hypomorphPatchBodyGrowthDefect';
import type { HypomorphPatchBodyGrowthDefectSeverity } from './hypomorphPatchBodyGrowthDefectSeverity';
import type { HypomorphPatchBodyKnockdownStrainId } from './hypomorphPatchBodyKnockdownStrainId';
import type { HypomorphPatchBodyCondition } from './hypomorphPatchBodyCondition';
import type { HypomorphPatchBodyMethod } from './hypomorphPatchBodyMethod';
import type { HypomorphPatchBodyProvenance } from './hypomorphPatchBodyProvenance';
import type { HypomorphPatchBodyExtensions } from './hypomorphPatchBodyExtensions';
import type { HypomorphPatchBodyVersion } from './hypomorphPatchBodyVersion';

export interface HypomorphPatchBody {
  growth_defect?: HypomorphPatchBodyGrowthDefect;
  growth_defect_severity?: HypomorphPatchBodyGrowthDefectSeverity;
  knockdown_strain_id?: HypomorphPatchBodyKnockdownStrainId;
  condition?: HypomorphPatchBodyCondition;
  method?: HypomorphPatchBodyMethod;
  provenance?: HypomorphPatchBodyProvenance;
  extensions?: HypomorphPatchBodyExtensions;
  version?: HypomorphPatchBodyVersion;
}
