/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ImportType } from './importType';
import type { ImportStatus } from './importStatus';
import type { ImportRunResponsePhase } from './importRunResponsePhase';
import type { ImportRunResponseProgress } from './importRunResponseProgress';
import type { ImportRunResponseSummary } from './importRunResponseSummary';
import type { ImportRunResponseParams } from './importRunResponseParams';
import type { ImportRunResponseSourceVersion } from './importRunResponseSourceVersion';
import type { ImportRunResponseError } from './importRunResponseError';
import type { ImportRunResponseUploadRef } from './importRunResponseUploadRef';
import type { ImportRunResponseStartedAt } from './importRunResponseStartedAt';
import type { ImportRunResponseFinishedAt } from './importRunResponseFinishedAt';

export interface ImportRunResponse {
  id: string;
  import_type: ImportType;
  target_key: string;
  status: ImportStatus;
  phase?: ImportRunResponsePhase;
  progress: ImportRunResponseProgress;
  summary: ImportRunResponseSummary;
  params: ImportRunResponseParams;
  source_version?: ImportRunResponseSourceVersion;
  error?: ImportRunResponseError;
  requested_by: string;
  upload_ref?: ImportRunResponseUploadRef;
  created_at: string;
  started_at?: ImportRunResponseStartedAt;
  finished_at?: ImportRunResponseFinishedAt;
}
