/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ImportType = typeof ImportType[keyof typeof ImportType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportType = {
  proteome: 'proteome',
  gene_enrichment: 'gene_enrichment',
  go_ontology: 'go_ontology',
  plugin: 'plugin',
} as const;
