/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { IsoformBodyName } from './isoformBodyName';
import type { IsoformBodySequence } from './isoformBodySequence';
import type { IsoformBodyEvent } from './isoformBodyEvent';
import type { IsoformBodyNote } from './isoformBodyNote';

export interface IsoformBody {
  isoform_accession: string;
  name?: IsoformBodyName;
  is_displayed?: boolean;
  sequence?: IsoformBodySequence;
  event?: IsoformBodyEvent;
  note?: IsoformBodyNote;
}
