/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { IsoformResponseName } from './isoformResponseName';
import type { IsoformResponseSequence } from './isoformResponseSequence';
import type { IsoformResponseEvent } from './isoformResponseEvent';
import type { IsoformResponseNote } from './isoformResponseNote';

export interface IsoformResponse {
  isoform_accession: string;
  name?: IsoformResponseName;
  is_displayed?: boolean;
  sequence?: IsoformResponseSequence;
  event?: IsoformResponseEvent;
  note?: IsoformResponseNote;
}
