/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ItemResultResponseId } from './itemResultResponseId';
import type { ItemResultResponseError } from './itemResultResponseError';

export interface ItemResultResponse {
  index: number;
  status: string;
  id?: ItemResultResponseId;
  error?: ItemResultResponseError;
}
