/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { KeywordRefBodyName } from './keywordRefBodyName';
import type { KeywordRefBodyCategory } from './keywordRefBodyCategory';

export interface KeywordRefBody {
  kw_id: string;
  name?: KeywordRefBodyName;
  category?: KeywordRefBodyCategory;
}
