/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListOrganismsApiV1OrganismsGetTagLogic = typeof ListOrganismsApiV1OrganismsGetTagLogic[keyof typeof ListOrganismsApiV1OrganismsGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListOrganismsApiV1OrganismsGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
