/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListProteinsApiV1ProteinsGetTagLogic = typeof ListProteinsApiV1ProteinsGetTagLogic[keyof typeof ListProteinsApiV1ProteinsGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListProteinsApiV1ProteinsGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
