/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListTargetBiologyApiV1TargetBiologyKindGetParams = {
organism_id?: string | null;
strain_id?: string | null;
gene_id?: string[] | null;
protein_id?: string[] | null;
cursor?: string | null;
limit?: number | null;
};
