/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListStrainsApiV1StrainsGetTagLogic = typeof ListStrainsApiV1StrainsGetTagLogic[keyof typeof ListStrainsApiV1StrainsGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListStrainsApiV1StrainsGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
