/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListOrganismsApiV1OrganismsGetParams = {
name?: string | null;
rank?: string | null;
cursor?: string | null;
limit?: number | null;
};
