/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListGenesApiV1GenesGetTagLogic = typeof ListGenesApiV1GenesGetTagLogic[keyof typeof ListGenesApiV1GenesGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListGenesApiV1GenesGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
