/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListProteomesApiV1ProteomesGetParams = {
organism_id?: string | null;
cursor?: string | null;
limit?: number | null;
};
