/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListProteomesApiV1ProteomesGetTagLogic = typeof ListProteomesApiV1ProteomesGetTagLogic[keyof typeof ListProteomesApiV1ProteomesGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListProteomesApiV1ProteomesGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
