/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ListProteinsApiV1ProteinsGetTagLogic } from './listProteinsApiV1ProteinsGetTagLogic';

export type ListProteinsApiV1ProteinsGetParams = {
organism_id?: string | null;
strain_id?: string | null;
gene_id?: string | null;
reviewed?: boolean | null;
min_length?: number | null;
max_length?: number | null;
xref_db?: string | null;
has_structure?: boolean | null;
is_enzyme?: boolean | null;
go_term?: string | null;
descendants?: boolean;
keyword?: string | null;
q?: string | null;
tags?: string[] | null;
tag_logic?: ListProteinsApiV1ProteinsGetTagLogic;
cursor?: string | null;
limit?: number | null;
};
