/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListProteinsApiV1ProteinsGetParams = {
organism_id?: string | null;
gene_id?: string | null;
reviewed?: boolean | null;
min_length?: number | null;
max_length?: number | null;
cursor?: string | null;
limit?: number | null;
};
