/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ListTargetsApiV1TargetsGetTagLogic = typeof ListTargetsApiV1TargetsGetTagLogic[keyof typeof ListTargetsApiV1TargetsGetTagLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListTargetsApiV1TargetsGetTagLogic = {
  any: 'any',
  all: 'all',
} as const;
