/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { TargetType } from './targetType';

export type ListTargetsApiV1TargetsGetParams = {
target_type?: TargetType | null;
chembl_id?: string | null;
cursor?: string | null;
limit?: number | null;
};
