/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationType } from './organizationType';
import type { OrganizationResponseContactName } from './organizationResponseContactName';
import type { OrganizationResponseContactEmail } from './organizationResponseContactEmail';
import type { OrganizationResponseNotes } from './organizationResponseNotes';

export interface OrganizationResponse {
  id: string;
  workspace_id: string;
  name: string;
  org_type: OrganizationType;
  contact_name?: OrganizationResponseContactName;
  contact_email?: OrganizationResponseContactEmail;
  notes?: OrganizationResponseNotes;
  is_active: boolean;
  version: number;
}
