/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OrganismResponseNcbiTaxId } from './organismResponseNcbiTaxId';
import type { OrganismResponseNcbiUrl } from './organismResponseNcbiUrl';
import type { OrganismResponseParentId } from './organismResponseParentId';
import type { OrganismResponseDivision } from './organismResponseDivision';
import type { OrganismResponseReferenceStrainId } from './organismResponseReferenceStrainId';
import type { OrganismResponseMergedIntoId } from './organismResponseMergedIntoId';
import type { OrganismSource } from './organismSource';
import type { OrganismResponseSourceRelease } from './organismResponseSourceRelease';
import type { OrganismNameResponse } from './organismNameResponse';

export interface OrganismResponse {
  id: string;
  ncbi_tax_id?: OrganismResponseNcbiTaxId;
  ncbi_url?: OrganismResponseNcbiUrl;
  parent_id?: OrganismResponseParentId;
  rank: string;
  scientific_name: string;
  division?: OrganismResponseDivision;
  reference_strain_id?: OrganismResponseReferenceStrainId;
  is_merged: boolean;
  merged_into_id?: OrganismResponseMergedIntoId;
  is_deleted: boolean;
  source: OrganismSource;
  source_release?: OrganismResponseSourceRelease;
  version: number;
  names: OrganismNameResponse[];
}
