/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { StrainResponse } from './strainResponse';
import type { PaginatedResponseStrainResponseNextCursor } from './paginatedResponseStrainResponseNextCursor';
import type { PaginatedResponseStrainResponseTotalCount } from './paginatedResponseStrainResponseTotalCount';

export interface PaginatedResponseStrainResponse {
  items: StrainResponse[];
  next_cursor?: PaginatedResponseStrainResponseNextCursor;
  total_count?: PaginatedResponseStrainResponseTotalCount;
}
