/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteomeResponse } from './proteomeResponse';
import type { PaginatedResponseProteomeResponseNextCursor } from './paginatedResponseProteomeResponseNextCursor';
import type { PaginatedResponseProteomeResponseTotalCount } from './paginatedResponseProteomeResponseTotalCount';

export interface PaginatedResponseProteomeResponse {
  items: ProteomeResponse[];
  next_cursor?: PaginatedResponseProteomeResponseNextCursor;
  total_count?: PaginatedResponseProteomeResponseTotalCount;
}
