/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { GeneResponse } from './geneResponse';
import type { PaginatedResponseGeneResponseNextCursor } from './paginatedResponseGeneResponseNextCursor';
import type { PaginatedResponseGeneResponseTotalCount } from './paginatedResponseGeneResponseTotalCount';

export interface PaginatedResponseGeneResponse {
  items: GeneResponse[];
  next_cursor?: PaginatedResponseGeneResponseNextCursor;
  total_count?: PaginatedResponseGeneResponseTotalCount;
}
