/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinResponse } from './proteinResponse';
import type { PaginatedResponseProteinResponseNextCursor } from './paginatedResponseProteinResponseNextCursor';
import type { PaginatedResponseProteinResponseTotalCount } from './paginatedResponseProteinResponseTotalCount';

export interface PaginatedResponseProteinResponse {
  items: ProteinResponse[];
  next_cursor?: PaginatedResponseProteinResponseNextCursor;
  total_count?: PaginatedResponseProteinResponseTotalCount;
}
