/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OrganizationResponse } from './organizationResponse';
import type { PaginatedResponseOrganizationResponseNextCursor } from './paginatedResponseOrganizationResponseNextCursor';
import type { PaginatedResponseOrganizationResponseTotalCount } from './paginatedResponseOrganizationResponseTotalCount';

export interface PaginatedResponseOrganizationResponse {
  items: OrganizationResponse[];
  next_cursor?: PaginatedResponseOrganizationResponseNextCursor;
  total_count?: PaginatedResponseOrganizationResponseTotalCount;
}
