/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { OrganismResponse } from './organismResponse';
import type { PaginatedResponseOrganismResponseNextCursor } from './paginatedResponseOrganismResponseNextCursor';
import type { PaginatedResponseOrganismResponseTotalCount } from './paginatedResponseOrganismResponseTotalCount';

export interface PaginatedResponseOrganismResponse {
  items: OrganismResponse[];
  next_cursor?: PaginatedResponseOrganismResponseNextCursor;
  total_count?: PaginatedResponseOrganismResponseTotalCount;
}
