/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { TargetResponse } from './targetResponse';
import type { PaginatedResponseTargetResponseNextCursor } from './paginatedResponseTargetResponseNextCursor';
import type { PaginatedResponseTargetResponseTotalCount } from './paginatedResponseTargetResponseTotalCount';

export interface PaginatedResponseTargetResponse {
  items: TargetResponse[];
  next_cursor?: PaginatedResponseTargetResponseNextCursor;
  total_count?: PaginatedResponseTargetResponseTotalCount;
}
