/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinListItemResponse } from './proteinListItemResponse';
import type { PaginatedResponseProteinListItemResponseNextCursor } from './paginatedResponseProteinListItemResponseNextCursor';
import type { PaginatedResponseProteinListItemResponseTotalCount } from './paginatedResponseProteinListItemResponseTotalCount';

export interface PaginatedResponseProteinListItemResponse {
  items: ProteinListItemResponse[];
  next_cursor?: PaginatedResponseProteinListItemResponseNextCursor;
  total_count?: PaginatedResponseProteinListItemResponseTotalCount;
}
