/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ImportRunResponse } from './importRunResponse';
import type { PaginatedResponseImportRunResponseNextCursor } from './paginatedResponseImportRunResponseNextCursor';
import type { PaginatedResponseImportRunResponseTotalCount } from './paginatedResponseImportRunResponseTotalCount';

export interface PaginatedResponseImportRunResponse {
  items: ImportRunResponse[];
  next_cursor?: PaginatedResponseImportRunResponseNextCursor;
  total_count?: PaginatedResponseImportRunResponseTotalCount;
}
