/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ParamFieldResponse } from './paramFieldResponse';

export interface PluginManifestResponse {
  id: string;
  version: string;
  name: string;
  description: string;
  target_records: string[];
  default_generation_method: string;
  params: ParamFieldResponse[];
  requires_secrets: string[];
  enabled: boolean;
}
