/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinActivityAssayWriteBodyActivityMeasured } from './proteinActivityAssayWriteBodyActivityMeasured';
import type { ProteinActivityAssayWriteBodyReadout } from './proteinActivityAssayWriteBodyReadout';
import type { ProteinActivityAssayWriteBodyThroughput } from './proteinActivityAssayWriteBodyThroughput';
import type { ProteinActivityAssayWriteBodyCondition } from './proteinActivityAssayWriteBodyCondition';
import type { ProteinActivityAssayWriteBodyMethod } from './proteinActivityAssayWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';
import type { ProteinActivityAssayWriteBodyExtensions } from './proteinActivityAssayWriteBodyExtensions';

export interface ProteinActivityAssayWriteBody {
  activity_measured?: ProteinActivityAssayWriteBodyActivityMeasured;
  readout?: ProteinActivityAssayWriteBodyReadout;
  throughput?: ProteinActivityAssayWriteBodyThroughput;
  condition?: ProteinActivityAssayWriteBodyCondition;
  method?: ProteinActivityAssayWriteBodyMethod;
  provenance: ProvenanceBody;
  extensions?: ProteinActivityAssayWriteBodyExtensions;
}
