/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProtcellarInterfaceRoutesOrganismsBulkRecordBodyNcbiTaxId } from './protcellarInterfaceRoutesOrganismsBulkRecordBodyNcbiTaxId';
import type { ProtcellarInterfaceRoutesOrganismsBulkRecordBodyDivision } from './protcellarInterfaceRoutesOrganismsBulkRecordBodyDivision';

export interface ProtcellarInterfaceRoutesOrganismsBulkRecordBody {
  ncbi_tax_id?: ProtcellarInterfaceRoutesOrganismsBulkRecordBodyNcbiTaxId;
  rank: string;
  scientific_name: string;
  source: string;
  source_release: string;
  source_record_id: string;
  source_record_checksum: string;
  division?: ProtcellarInterfaceRoutesOrganismsBulkRecordBodyDivision;
}
