/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyEntryName } from './protcellarInterfaceRoutesProteinsBulkRecordBodyEntryName';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyProteinNames } from './protcellarInterfaceRoutesProteinsBulkRecordBodyProteinNames';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyStrainId } from './protcellarInterfaceRoutesProteinsBulkRecordBodyStrainId';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyGeneId } from './protcellarInterfaceRoutesProteinsBulkRecordBodyGeneId';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodySeqMass } from './protcellarInterfaceRoutesProteinsBulkRecordBodySeqMass';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodySeqCrc64 } from './protcellarInterfaceRoutesProteinsBulkRecordBodySeqCrc64';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyProteinExistence } from './protcellarInterfaceRoutesProteinsBulkRecordBodyProteinExistence';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodyEntryVersion } from './protcellarInterfaceRoutesProteinsBulkRecordBodyEntryVersion';
import type { ProtcellarInterfaceRoutesProteinsBulkRecordBodySequenceVersion } from './protcellarInterfaceRoutesProteinsBulkRecordBodySequenceVersion';
import type { CrossReferenceBody } from './crossReferenceBody';

export interface ProtcellarInterfaceRoutesProteinsBulkRecordBody {
  primary_accession: string;
  organism_id: string;
  sequence: string;
  is_reviewed: boolean;
  source: string;
  source_release: string;
  source_record_id: string;
  source_record_checksum: string;
  secondary_accessions?: string[];
  entry_name?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyEntryName;
  protein_names?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyProteinNames;
  strain_id?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyStrainId;
  gene_id?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyGeneId;
  seq_mass?: ProtcellarInterfaceRoutesProteinsBulkRecordBodySeqMass;
  seq_crc64?: ProtcellarInterfaceRoutesProteinsBulkRecordBodySeqCrc64;
  protein_existence?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyProteinExistence;
  keywords?: string[];
  entry_version?: ProtcellarInterfaceRoutesProteinsBulkRecordBodyEntryVersion;
  sequence_version?: ProtcellarInterfaceRoutesProteinsBulkRecordBodySequenceVersion;
  cross_references?: CrossReferenceBody[];
}
