/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProtcellarInterfaceRoutesOrganismsBulkRecordBody } from './protcellarInterfaceRoutesOrganismsBulkRecordBody';

export interface ProtcellarInterfaceRoutesOrganismsBulkUpsertBody {
  records: ProtcellarInterfaceRoutesOrganismsBulkRecordBody[];
  dry_run?: boolean;
}
