/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinListItemResponseUniprotUrl } from './proteinListItemResponseUniprotUrl';
import type { ProteinListItemResponseEntryName } from './proteinListItemResponseEntryName';
import type { ProteinListItemResponseRecommendedName } from './proteinListItemResponseRecommendedName';
import type { ProteinListItemResponseGene } from './proteinListItemResponseGene';
import type { ProteinListItemResponseStrainId } from './proteinListItemResponseStrainId';
import type { ProteinListItemResponseSeqMass } from './proteinListItemResponseSeqMass';
import type { ProteinListItemResponseProteinExistence } from './proteinListItemResponseProteinExistence';
import type { ProteinStructureSummary } from './proteinStructureSummary';
import type { ProteinChemSummary } from './proteinChemSummary';

/**
 * Decision-oriented projection of a protein for the catalog list (target triage).

Deliberately slimmer than :class:`ProteinResponse`: it carries only what the list
table needs plus derived structure / chemical-matter flags, so a page of rows stays
light instead of shipping every feature, comment and citation per row.
 */
export interface ProteinListItemResponse {
  id: string;
  primary_accession: string;
  uniprot_url?: ProteinListItemResponseUniprotUrl;
  entry_name?: ProteinListItemResponseEntryName;
  is_reviewed: boolean;
  recommended_name?: ProteinListItemResponseRecommendedName;
  short_names?: string[];
  ec_numbers?: string[];
  gene?: ProteinListItemResponseGene;
  organism_id: string;
  strain_id?: ProteinListItemResponseStrainId;
  seq_length: number;
  seq_mass?: ProteinListItemResponseSeqMass;
  protein_existence?: ProteinListItemResponseProteinExistence;
  structure: ProteinStructureSummary;
  chem: ProteinChemSummary;
}
