/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinProductionPatchBodyStatus } from './proteinProductionPatchBodyStatus';
import type { ProteinProductionPatchBodyExpressionHost } from './proteinProductionPatchBodyExpressionHost';
import type { ProteinProductionPatchBodyPurity } from './proteinProductionPatchBodyPurity';
import type { ProteinProductionPatchBodyCondition } from './proteinProductionPatchBodyCondition';
import type { ProteinProductionPatchBodyMethod } from './proteinProductionPatchBodyMethod';
import type { ProteinProductionPatchBodyProvenance } from './proteinProductionPatchBodyProvenance';
import type { ProteinProductionPatchBodyVersion } from './proteinProductionPatchBodyVersion';

export interface ProteinProductionPatchBody {
  status?: ProteinProductionPatchBodyStatus;
  expression_host?: ProteinProductionPatchBodyExpressionHost;
  purity?: ProteinProductionPatchBodyPurity;
  condition?: ProteinProductionPatchBodyCondition;
  method?: ProteinProductionPatchBodyMethod;
  provenance?: ProteinProductionPatchBodyProvenance;
  version?: ProteinProductionPatchBodyVersion;
}
