/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteomeResponseProteomeUrl } from './proteomeResponseProteomeUrl';
import type { ProteomeResponseStrainId } from './proteomeResponseStrainId';
import type { ProteomeType } from './proteomeType';
import type { ProteomeResponseAssemblyAcc } from './proteomeResponseAssemblyAcc';
import type { ProteomeResponseSourceVersion } from './proteomeResponseSourceVersion';
import type { ProteomeResponseOrganismName } from './proteomeResponseOrganismName';
import type { ProteomeResponseStrainName } from './proteomeResponseStrainName';

export interface ProteomeResponse {
  id: string;
  uniprot_proteome_id: string;
  proteome_url?: ProteomeResponseProteomeUrl;
  organism_id: string;
  strain_id?: ProteomeResponseStrainId;
  proteome_type: ProteomeType;
  is_reference: boolean;
  assembly_acc?: ProteomeResponseAssemblyAcc;
  source_version?: ProteomeResponseSourceVersion;
  version: number;
  organism_name?: ProteomeResponseOrganismName;
  strain_name?: ProteomeResponseStrainName;
}
