/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinProductionWriteBodyExpressionHost } from './proteinProductionWriteBodyExpressionHost';
import type { ProteinProductionWriteBodyPurity } from './proteinProductionWriteBodyPurity';
import type { ProteinProductionWriteBodyCondition } from './proteinProductionWriteBodyCondition';
import type { ProteinProductionWriteBodyMethod } from './proteinProductionWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';

export interface ProteinProductionWriteBody {
  status: string;
  expression_host?: ProteinProductionWriteBodyExpressionHost;
  purity?: ProteinProductionWriteBodyPurity;
  condition?: ProteinProductionWriteBodyCondition;
  method?: ProteinProductionWriteBodyMethod;
  provenance: ProvenanceBody;
}
