/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinActivityAssayResponseReadout } from './proteinActivityAssayResponseReadout';
import type { ProteinActivityAssayResponseThroughput } from './proteinActivityAssayResponseThroughput';
import type { ProteinActivityAssayResponseCondition } from './proteinActivityAssayResponseCondition';
import type { ProteinActivityAssayResponseMethod } from './proteinActivityAssayResponseMethod';
import type { ProvenanceResponse } from './provenanceResponse';
import type { ProteinActivityAssayResponseExtensions } from './proteinActivityAssayResponseExtensions';

export interface ProteinActivityAssayResponse {
  id: string;
  protein_id: string;
  activity_measured: string;
  readout?: ProteinActivityAssayResponseReadout;
  throughput?: ProteinActivityAssayResponseThroughput;
  condition?: ProteinActivityAssayResponseCondition;
  method?: ProteinActivityAssayResponseMethod;
  provenance: ProvenanceResponse;
  extensions: ProteinActivityAssayResponseExtensions;
  version: number;
  is_shared: boolean;
}
