/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * 3D-structure availability, distilled for at-a-glance druggability triage.
 */
export interface ProteinStructureSummary {
  pdb_count: number;
  has_alphafold: boolean;
}
