/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type ProteinExistence = typeof ProteinExistence[keyof typeof ProteinExistence];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProteinExistence = {
  evidence_at_protein_level: 'evidence_at_protein_level',
  evidence_at_transcript_level: 'evidence_at_transcript_level',
  inferred_from_homology: 'inferred_from_homology',
  predicted: 'predicted',
  uncertain: 'uncertain',
} as const;
