/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinActivityAssayPatchBodyActivityMeasured } from './proteinActivityAssayPatchBodyActivityMeasured';
import type { ProteinActivityAssayPatchBodyReadout } from './proteinActivityAssayPatchBodyReadout';
import type { ProteinActivityAssayPatchBodyThroughput } from './proteinActivityAssayPatchBodyThroughput';
import type { ProteinActivityAssayPatchBodyCondition } from './proteinActivityAssayPatchBodyCondition';
import type { ProteinActivityAssayPatchBodyMethod } from './proteinActivityAssayPatchBodyMethod';
import type { ProteinActivityAssayPatchBodyProvenance } from './proteinActivityAssayPatchBodyProvenance';
import type { ProteinActivityAssayPatchBodyVersion } from './proteinActivityAssayPatchBodyVersion';

export interface ProteinActivityAssayPatchBody {
  activity_measured?: ProteinActivityAssayPatchBodyActivityMeasured;
  readout?: ProteinActivityAssayPatchBodyReadout;
  throughput?: ProteinActivityAssayPatchBodyThroughput;
  condition?: ProteinActivityAssayPatchBodyCondition;
  method?: ProteinActivityAssayPatchBodyMethod;
  provenance?: ProteinActivityAssayPatchBodyProvenance;
  version?: ProteinActivityAssayPatchBodyVersion;
}
