/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinProductionResponse } from './proteinProductionResponse';
import type { ProteinActivityAssayResponse } from './proteinActivityAssayResponse';
import type { UnpublishedStructureResponse } from './unpublishedStructureResponse';

export interface ProteinTargetBiologyResponse {
  protein_production: ProteinProductionResponse[];
  protein_activity_assay: ProteinActivityAssayResponse[];
  unpublished_structure: UnpublishedStructureResponse[];
}
