/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinNamesBodyRecommended } from './proteinNamesBodyRecommended';

export interface ProteinNamesBody {
  recommended?: ProteinNamesBodyRecommended;
  alternative?: string[];
  submitted?: string[];
  short_names?: string[];
  ec_numbers?: string[];
}
