/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinProductionResponseStatus } from './proteinProductionResponseStatus';
import type { ProteinProductionResponseExpressionHost } from './proteinProductionResponseExpressionHost';
import type { ProteinProductionResponsePurity } from './proteinProductionResponsePurity';
import type { ProteinProductionResponseCondition } from './proteinProductionResponseCondition';
import type { ProteinProductionResponseMethod } from './proteinProductionResponseMethod';
import type { ProvenanceResponse } from './provenanceResponse';
import type { ProteinProductionResponseExtensions } from './proteinProductionResponseExtensions';

export interface ProteinProductionResponse {
  id: string;
  protein_id: string;
  status?: ProteinProductionResponseStatus;
  expression_host?: ProteinProductionResponseExpressionHost;
  purity?: ProteinProductionResponsePurity;
  condition?: ProteinProductionResponseCondition;
  method?: ProteinProductionResponseMethod;
  provenance: ProvenanceResponse;
  extensions: ProteinProductionResponseExtensions;
  version: number;
  is_shared: boolean;
}
