/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinXrefResponseCurie } from './proteinXrefResponseCurie';
import type { ProteinXrefResponseUrl } from './proteinXrefResponseUrl';
import type { ProteinXrefResponseProperties } from './proteinXrefResponseProperties';

export interface ProteinXrefResponse {
  database: string;
  accession: string;
  curie?: ProteinXrefResponseCurie;
  url?: ProteinXrefResponseUrl;
  properties?: ProteinXrefResponseProperties;
}
