/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

/**
 * Presence of chemical matter (known ligands / bioactivity) for a protein.
 */
export interface ProteinChemSummary {
  has_chembl: boolean;
  has_drugbank: boolean;
}
