/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinResponseUniprotUrl } from './proteinResponseUniprotUrl';
import type { ProteinResponseEntryName } from './proteinResponseEntryName';
import type { ProteinResponseProteinNames } from './proteinResponseProteinNames';
import type { ProteinResponseStrainId } from './proteinResponseStrainId';
import type { ProteinResponseGeneId } from './proteinResponseGeneId';
import type { ProteinResponseSeqMass } from './proteinResponseSeqMass';
import type { ProteinResponseSeqCrc64 } from './proteinResponseSeqCrc64';
import type { ProteinResponseProteinExistence } from './proteinResponseProteinExistence';
import type { ProteinResponseEntryVersion } from './proteinResponseEntryVersion';
import type { ProteinResponseSequenceVersion } from './proteinResponseSequenceVersion';
import type { ProteinXrefResponse } from './proteinXrefResponse';
import type { ProteinResponseAnnotationScore } from './proteinResponseAnnotationScore';
import type { ProteinResponseFragment } from './proteinResponseFragment';
import type { ProteinResponseUniparcId } from './proteinResponseUniparcId';
import type { FeatureResponse } from './featureResponse';
import type { CommentResponse } from './commentResponse';
import type { IsoformResponse } from './isoformResponse';
import type { KeywordRefResponse } from './keywordRefResponse';
import type { CitationResponse } from './citationResponse';

export interface ProteinResponse {
  id: string;
  primary_accession: string;
  uniprot_url?: ProteinResponseUniprotUrl;
  secondary_accessions: string[];
  entry_name?: ProteinResponseEntryName;
  is_reviewed: boolean;
  protein_names: ProteinResponseProteinNames;
  organism_id: string;
  strain_id?: ProteinResponseStrainId;
  gene_id?: ProteinResponseGeneId;
  seq_length: number;
  seq_mass?: ProteinResponseSeqMass;
  seq_crc64?: ProteinResponseSeqCrc64;
  protein_existence?: ProteinResponseProteinExistence;
  keywords: string[];
  entry_version?: ProteinResponseEntryVersion;
  sequence_version?: ProteinResponseSequenceVersion;
  cross_references: ProteinXrefResponse[];
  annotation_score?: ProteinResponseAnnotationScore;
  fragment?: ProteinResponseFragment;
  uniparc_id?: ProteinResponseUniparcId;
  features?: FeatureResponse[];
  comments?: CommentResponse[];
  isoforms?: IsoformResponse[];
  keyword_refs?: KeywordRefResponse[];
  citations?: CitationResponse[];
  version: number;
}
