/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProteinActivityAssayWriteBodyReadout } from './proteinActivityAssayWriteBodyReadout';
import type { ProteinActivityAssayWriteBodyThroughput } from './proteinActivityAssayWriteBodyThroughput';
import type { ProteinActivityAssayWriteBodyCondition } from './proteinActivityAssayWriteBodyCondition';
import type { ProteinActivityAssayWriteBodyMethod } from './proteinActivityAssayWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';

export interface ProteinActivityAssayWriteBody {
  activity_measured: string;
  readout?: ProteinActivityAssayWriteBodyReadout;
  throughput?: ProteinActivityAssayWriteBodyThroughput;
  condition?: ProteinActivityAssayWriteBodyCondition;
  method?: ProteinActivityAssayWriteBodyMethod;
  provenance: ProvenanceBody;
}
