/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProvenanceCitationBodyPmid } from './provenanceCitationBodyPmid';
import type { ProvenanceCitationBodyDoi } from './provenanceCitationBodyDoi';
import type { ProvenanceCitationBodyUrl } from './provenanceCitationBodyUrl';
import type { ProvenanceCitationBodyLabel } from './provenanceCitationBodyLabel';

export interface ProvenanceCitationBody {
  pmid?: ProvenanceCitationBodyPmid;
  doi?: ProvenanceCitationBodyDoi;
  url?: ProvenanceCitationBodyUrl;
  label?: ProvenanceCitationBodyLabel;
}
