/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ProvenanceCitationResponse } from './provenanceCitationResponse';
import type { ProvenanceResponseContributorResearcher } from './provenanceResponseContributorResearcher';
import type { ProvenanceResponseContributorOrganizationId } from './provenanceResponseContributorOrganizationId';
import type { ProvenanceResponseObservedOn } from './provenanceResponseObservedOn';
import type { ProvenanceResponseNote } from './provenanceResponseNote';

export interface ProvenanceResponse {
  source_type: string;
  citations: ProvenanceCitationResponse[];
  contributor_researcher?: ProvenanceResponseContributorResearcher;
  contributor_organization_id?: ProvenanceResponseContributorOrganizationId;
  observed_on?: ProvenanceResponseObservedOn;
  note?: ProvenanceResponseNote;
}
