/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type RecordKind = typeof RecordKind[keyof typeof RecordKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecordKind = {
  essentiality: 'essentiality',
  vulnerability: 'vulnerability',
  hypomorph: 'hypomorph',
  crispri_strain: 'crispri_strain',
  resistance_mutation: 'resistance_mutation',
  protein_production: 'protein_production',
  protein_activity_assay: 'protein_activity_assay',
  unpublished_structure: 'unpublished_structure',
} as const;
