/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ResistanceMutationWriteBodyCompound } from './resistanceMutationWriteBodyCompound';
import type { ResistanceMutationWriteBodyMicShift } from './resistanceMutationWriteBodyMicShift';
import type { ResistanceMutationWriteBodyParentStrain } from './resistanceMutationWriteBodyParentStrain';
import type { ResistanceMutationWriteBodyProteinCoordinate } from './resistanceMutationWriteBodyProteinCoordinate';
import type { ResistanceMutationWriteBodyMethod } from './resistanceMutationWriteBodyMethod';
import type { ProvenanceBody } from './provenanceBody';

export interface ResistanceMutationWriteBody {
  mutation: string;
  compound?: ResistanceMutationWriteBodyCompound;
  mic_shift?: ResistanceMutationWriteBodyMicShift;
  parent_strain?: ResistanceMutationWriteBodyParentStrain;
  protein_coordinate?: ResistanceMutationWriteBodyProteinCoordinate;
  method?: ResistanceMutationWriteBodyMethod;
  provenance: ProvenanceBody;
}
