/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ResistanceMutationResponseCompound } from './resistanceMutationResponseCompound';
import type { ResistanceMutationResponseMicShift } from './resistanceMutationResponseMicShift';
import type { ResistanceMutationResponseParentStrain } from './resistanceMutationResponseParentStrain';
import type { ResistanceMutationResponseProteinCoordinate } from './resistanceMutationResponseProteinCoordinate';
import type { ResistanceMutationResponseMethod } from './resistanceMutationResponseMethod';
import type { ProvenanceResponse } from './provenanceResponse';
import type { ResistanceMutationResponseExtensions } from './resistanceMutationResponseExtensions';

export interface ResistanceMutationResponse {
  id: string;
  gene_id: string;
  mutation: string;
  compound?: ResistanceMutationResponseCompound;
  mic_shift?: ResistanceMutationResponseMicShift;
  parent_strain?: ResistanceMutationResponseParentStrain;
  protein_coordinate?: ResistanceMutationResponseProteinCoordinate;
  method?: ResistanceMutationResponseMethod;
  provenance: ProvenanceResponse;
  extensions: ResistanceMutationResponseExtensions;
  version: number;
  is_shared: boolean;
}
