/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { ResistanceMutationPatchBodyMutation } from './resistanceMutationPatchBodyMutation';
import type { ResistanceMutationPatchBodyCompound } from './resistanceMutationPatchBodyCompound';
import type { ResistanceMutationPatchBodyMicShift } from './resistanceMutationPatchBodyMicShift';
import type { ResistanceMutationPatchBodyParentStrain } from './resistanceMutationPatchBodyParentStrain';
import type { ResistanceMutationPatchBodyProteinCoordinate } from './resistanceMutationPatchBodyProteinCoordinate';
import type { ResistanceMutationPatchBodyMethod } from './resistanceMutationPatchBodyMethod';
import type { ResistanceMutationPatchBodyProvenance } from './resistanceMutationPatchBodyProvenance';
import type { ResistanceMutationPatchBodyVersion } from './resistanceMutationPatchBodyVersion';

export interface ResistanceMutationPatchBody {
  mutation?: ResistanceMutationPatchBodyMutation;
  compound?: ResistanceMutationPatchBodyCompound;
  mic_shift?: ResistanceMutationPatchBodyMicShift;
  parent_strain?: ResistanceMutationPatchBodyParentStrain;
  protein_coordinate?: ResistanceMutationPatchBodyProteinCoordinate;
  method?: ResistanceMutationPatchBodyMethod;
  provenance?: ResistanceMutationPatchBodyProvenance;
  version?: ResistanceMutationPatchBodyVersion;
}
