/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { StrainResponseStrainOrganismId } from './strainResponseStrainOrganismId';
import type { StrainResponseIsolate } from './strainResponseIsolate';
import type { StrainResponseBiosampleAcc } from './strainResponseBiosampleAcc';
import type { StrainResponseAssemblyAcc } from './strainResponseAssemblyAcc';
import type { StrainResponseCultureCollection } from './strainResponseCultureCollection';
import type { StrainResponseHostOrganismId } from './strainResponseHostOrganismId';
import type { StrainResponseMetadata } from './strainResponseMetadata';

export interface StrainResponse {
  id: string;
  workspace_id: string;
  species_organism_id: string;
  strain_organism_id?: StrainResponseStrainOrganismId;
  name: string;
  isolate?: StrainResponseIsolate;
  biosample_acc?: StrainResponseBiosampleAcc;
  assembly_acc?: StrainResponseAssemblyAcc;
  culture_collection?: StrainResponseCultureCollection;
  host_organism_id?: StrainResponseHostOrganismId;
  metadata?: StrainResponseMetadata;
  version: number;
}
