/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export interface TaggedEntityResponse {
  entity_type: string;
  entity_id: string;
  label: string;
  assigned_at: string;
}
