/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { TagResponseValue } from './tagResponseValue';

export interface TagResponse {
  id: string;
  workspace_id: string;
  key: string;
  value: TagResponseValue;
  created_by: string;
  created_at: string;
}
