/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export type TargetType = typeof TargetType[keyof typeof TargetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetType = {
  single_protein: 'single_protein',
  protein_complex: 'protein_complex',
  protein_family: 'protein_family',
  protein_protein_interaction: 'protein_protein_interaction',
  nucleic_acid: 'nucleic_acid',
  organism: 'organism',
  cell_line: 'cell_line',
  tissue: 'tissue',
  unknown: 'unknown',
} as const;
