/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { TargetType } from './targetType';
import type { ComponentResponse } from './componentResponse';
import type { TargetResponseOrganismId } from './targetResponseOrganismId';
import type { TargetResponseChemblId } from './targetResponseChemblId';
import type { TargetResponseChemblUrl } from './targetResponseChemblUrl';
import type { TargetResponsePharmacologicalClass } from './targetResponsePharmacologicalClass';
import type { TargetResponseCrossReferencesItem } from './targetResponseCrossReferencesItem';

export interface TargetResponse {
  id: string;
  workspace_id: string;
  pref_name: string;
  target_type: TargetType;
  components: ComponentResponse[];
  organism_id?: TargetResponseOrganismId;
  chembl_id?: TargetResponseChemblId;
  chembl_url?: TargetResponseChemblUrl;
  pharmacological_class?: TargetResponsePharmacologicalClass;
  cross_references: TargetResponseCrossReferencesItem[];
  version: number;
}
