/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UnpublishedStructureResponseMethod } from './unpublishedStructureResponseMethod';
import type { UnpublishedStructureResponseResolution } from './unpublishedStructureResponseResolution';
import type { CompoundRefResponse } from './compoundRefResponse';
import type { ProvenanceResponse } from './provenanceResponse';
import type { UnpublishedStructureResponseExtensions } from './unpublishedStructureResponseExtensions';

export interface UnpublishedStructureResponse {
  id: string;
  protein_id: string;
  method?: UnpublishedStructureResponseMethod;
  resolution?: UnpublishedStructureResponseResolution;
  ligands: CompoundRefResponse[];
  is_published: boolean;
  is_experimental: boolean;
  provenance: ProvenanceResponse;
  extensions: UnpublishedStructureResponseExtensions;
  version: number;
}
