/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UnpublishedStructurePatchBodyMethod } from './unpublishedStructurePatchBodyMethod';
import type { UnpublishedStructurePatchBodyResolution } from './unpublishedStructurePatchBodyResolution';
import type { UnpublishedStructurePatchBodyLigands } from './unpublishedStructurePatchBodyLigands';
import type { UnpublishedStructurePatchBodyIsPublished } from './unpublishedStructurePatchBodyIsPublished';
import type { UnpublishedStructurePatchBodyIsExperimental } from './unpublishedStructurePatchBodyIsExperimental';
import type { UnpublishedStructurePatchBodyProvenance } from './unpublishedStructurePatchBodyProvenance';
import type { UnpublishedStructurePatchBodyExtensions } from './unpublishedStructurePatchBodyExtensions';
import type { UnpublishedStructurePatchBodyVersion } from './unpublishedStructurePatchBodyVersion';

export interface UnpublishedStructurePatchBody {
  method?: UnpublishedStructurePatchBodyMethod;
  resolution?: UnpublishedStructurePatchBodyResolution;
  ligands?: UnpublishedStructurePatchBodyLigands;
  is_published?: UnpublishedStructurePatchBodyIsPublished;
  is_experimental?: UnpublishedStructurePatchBodyIsExperimental;
  provenance?: UnpublishedStructurePatchBodyProvenance;
  extensions?: UnpublishedStructurePatchBodyExtensions;
  version?: UnpublishedStructurePatchBodyVersion;
}
