/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UnpublishedStructureWriteBodyMethod } from './unpublishedStructureWriteBodyMethod';
import type { UnpublishedStructureWriteBodyResolution } from './unpublishedStructureWriteBodyResolution';
import type { ProvenanceBody } from './provenanceBody';

export interface UnpublishedStructureWriteBody {
  method?: UnpublishedStructureWriteBodyMethod;
  resolution?: UnpublishedStructureWriteBodyResolution;
  is_published?: boolean;
  is_experimental?: boolean;
  provenance: ProvenanceBody;
}
