/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateStrainBodyName } from './updateStrainBodyName';
import type { UpdateStrainBodyStrainOrganismId } from './updateStrainBodyStrainOrganismId';
import type { UpdateStrainBodyIsolate } from './updateStrainBodyIsolate';
import type { UpdateStrainBodyBiosampleAcc } from './updateStrainBodyBiosampleAcc';
import type { UpdateStrainBodyAssemblyAcc } from './updateStrainBodyAssemblyAcc';
import type { UpdateStrainBodyCultureCollection } from './updateStrainBodyCultureCollection';
import type { UpdateStrainBodyHostOrganismId } from './updateStrainBodyHostOrganismId';
import type { UpdateStrainBodyMetadata } from './updateStrainBodyMetadata';

export interface UpdateStrainBody {
  name?: UpdateStrainBodyName;
  strain_organism_id?: UpdateStrainBodyStrainOrganismId;
  isolate?: UpdateStrainBodyIsolate;
  biosample_acc?: UpdateStrainBodyBiosampleAcc;
  assembly_acc?: UpdateStrainBodyAssemblyAcc;
  culture_collection?: UpdateStrainBodyCultureCollection;
  host_organism_id?: UpdateStrainBodyHostOrganismId;
  metadata?: UpdateStrainBodyMetadata;
}
