/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateProteinBodySequence } from './updateProteinBodySequence';
import type { UpdateProteinBodyIsReviewed } from './updateProteinBodyIsReviewed';
import type { UpdateProteinBodySecondaryAccessions } from './updateProteinBodySecondaryAccessions';
import type { UpdateProteinBodyEntryName } from './updateProteinBodyEntryName';
import type { UpdateProteinBodyProteinNames } from './updateProteinBodyProteinNames';
import type { UpdateProteinBodyStrainId } from './updateProteinBodyStrainId';
import type { UpdateProteinBodyGeneId } from './updateProteinBodyGeneId';
import type { UpdateProteinBodySeqMass } from './updateProteinBodySeqMass';
import type { UpdateProteinBodySeqCrc64 } from './updateProteinBodySeqCrc64';
import type { UpdateProteinBodyProteinExistence } from './updateProteinBodyProteinExistence';
import type { UpdateProteinBodyKeywords } from './updateProteinBodyKeywords';
import type { UpdateProteinBodyEntryVersion } from './updateProteinBodyEntryVersion';
import type { UpdateProteinBodySequenceVersion } from './updateProteinBodySequenceVersion';
import type { UpdateProteinBodyCrossReferences } from './updateProteinBodyCrossReferences';

export interface UpdateProteinBody {
  sequence?: UpdateProteinBodySequence;
  is_reviewed?: UpdateProteinBodyIsReviewed;
  secondary_accessions?: UpdateProteinBodySecondaryAccessions;
  entry_name?: UpdateProteinBodyEntryName;
  protein_names?: UpdateProteinBodyProteinNames;
  strain_id?: UpdateProteinBodyStrainId;
  gene_id?: UpdateProteinBodyGeneId;
  seq_mass?: UpdateProteinBodySeqMass;
  seq_crc64?: UpdateProteinBodySeqCrc64;
  protein_existence?: UpdateProteinBodyProteinExistence;
  keywords?: UpdateProteinBodyKeywords;
  entry_version?: UpdateProteinBodyEntryVersion;
  sequence_version?: UpdateProteinBodySequenceVersion;
  cross_references?: UpdateProteinBodyCrossReferences;
}
