/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateFieldDefBodyLabel } from './updateFieldDefBodyLabel';
import type { UpdateFieldDefBodyFieldType } from './updateFieldDefBodyFieldType';
import type { UpdateFieldDefBodyOptions } from './updateFieldDefBodyOptions';
import type { UpdateFieldDefBodyPosition } from './updateFieldDefBodyPosition';
import type { UpdateFieldDefBodyShowInTable } from './updateFieldDefBodyShowInTable';

/**
 * ``name`` (and ``kind``) are deliberately absent: renaming would orphan every
stored value already keyed under the old name, and moving a declaration to a
different kind isn't a supported edit. Omitting the field from the body — not
a hand-rolled guard in the use case — is what turns a client's attempt to send
``name`` into a 422 (``extra="forbid"``), matching ``UpdateGeneBody``.
 */
export interface UpdateFieldDefBody {
  label?: UpdateFieldDefBodyLabel;
  field_type?: UpdateFieldDefBodyFieldType;
  options?: UpdateFieldDefBodyOptions;
  position?: UpdateFieldDefBodyPosition;
  show_in_table?: UpdateFieldDefBodyShowInTable;
}
