/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateTargetBodyPrefName } from './updateTargetBodyPrefName';
import type { UpdateTargetBodyTargetType } from './updateTargetBodyTargetType';
import type { UpdateTargetBodyComponents } from './updateTargetBodyComponents';
import type { UpdateTargetBodyOrganismId } from './updateTargetBodyOrganismId';
import type { UpdateTargetBodyChemblId } from './updateTargetBodyChemblId';
import type { UpdateTargetBodyPharmacologicalClass } from './updateTargetBodyPharmacologicalClass';
import type { UpdateTargetBodyCrossReferences } from './updateTargetBodyCrossReferences';

export interface UpdateTargetBody {
  pref_name?: UpdateTargetBodyPrefName;
  target_type?: UpdateTargetBodyTargetType;
  components?: UpdateTargetBodyComponents;
  organism_id?: UpdateTargetBodyOrganismId;
  chembl_id?: UpdateTargetBodyChemblId;
  pharmacological_class?: UpdateTargetBodyPharmacologicalClass;
  cross_references?: UpdateTargetBodyCrossReferences;
}
