/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateOrganismBodyScientificName } from './updateOrganismBodyScientificName';
import type { UpdateOrganismBodyRank } from './updateOrganismBodyRank';
import type { UpdateOrganismBodyParentId } from './updateOrganismBodyParentId';
import type { UpdateOrganismBodyDivision } from './updateOrganismBodyDivision';
import type { UpdateOrganismBodySourceVersion } from './updateOrganismBodySourceVersion';

export interface UpdateOrganismBody {
  scientific_name?: UpdateOrganismBodyScientificName;
  rank?: UpdateOrganismBodyRank;
  parent_id?: UpdateOrganismBodyParentId;
  division?: UpdateOrganismBodyDivision;
  source_version?: UpdateOrganismBodySourceVersion;
}
