/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateOrganizationBodyName } from './updateOrganizationBodyName';
import type { UpdateOrganizationBodyOrgType } from './updateOrganizationBodyOrgType';
import type { UpdateOrganizationBodyContactName } from './updateOrganizationBodyContactName';
import type { UpdateOrganizationBodyContactEmail } from './updateOrganizationBodyContactEmail';
import type { UpdateOrganizationBodyNotes } from './updateOrganizationBodyNotes';

export interface UpdateOrganizationBody {
  name?: UpdateOrganizationBodyName;
  org_type?: UpdateOrganizationBodyOrgType;
  contact_name?: UpdateOrganizationBodyContactName;
  contact_email?: UpdateOrganizationBodyContactEmail;
  notes?: UpdateOrganizationBodyNotes;
}
