/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateGeneBodyPrimaryName } from './updateGeneBodyPrimaryName';
import type { UpdateGeneBodySynonyms } from './updateGeneBodySynonyms';
import type { UpdateGeneBodyNcbiGeneId } from './updateGeneBodyNcbiGeneId';
import type { UpdateGeneBodyEnsemblGeneId } from './updateGeneBodyEnsemblGeneId';
import type { UpdateGeneBodyHgncId } from './updateGeneBodyHgncId';

export interface UpdateGeneBody {
  primary_name?: UpdateGeneBodyPrimaryName;
  synonyms?: UpdateGeneBodySynonyms;
  ncbi_gene_id?: UpdateGeneBodyNcbiGeneId;
  ensembl_gene_id?: UpdateGeneBodyEnsemblGeneId;
  hgnc_id?: UpdateGeneBodyHgncId;
}
