/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */

export interface VersionResponse {
  version: string;
  git_sha: string;
  build_date: string;
  environment: string;
}
