/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadEssentialityFileApiV1ImportsUploadsPost,
  HTTPValidationError,
  ImportRunResponse,
  ListImportRunsApiV1ImportsGetParams,
  PaginatedResponseImportRunResponse,
  StartImportBody,
  UploadEssentialityFileApiV1ImportsUploadsPostParams,
  UploadResponse
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary Start Import
 */
export const startImportApiV1ImportsPost = (
    startImportBody: StartImportBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ImportRunResponse>(
      {url: `/api/v1/imports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startImportBody, signal
    },
      );
    }
  


export const getStartImportApiV1ImportsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startImportApiV1ImportsPost>>, TError,{data: StartImportBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startImportApiV1ImportsPost>>, TError,{data: StartImportBody}, TContext> => {

const mutationKey = ['startImportApiV1ImportsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startImportApiV1ImportsPost>>, {data: StartImportBody}> = (props) => {
          const {data} = props ?? {};

          return  startImportApiV1ImportsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartImportApiV1ImportsPostMutationResult = NonNullable<Awaited<ReturnType<typeof startImportApiV1ImportsPost>>>
    export type StartImportApiV1ImportsPostMutationBody = StartImportBody
    export type StartImportApiV1ImportsPostMutationError = HTTPValidationError

    /**
 * @summary Start Import
 */
export const useStartImportApiV1ImportsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startImportApiV1ImportsPost>>, TError,{data: StartImportBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startImportApiV1ImportsPost>>,
        TError,
        {data: StartImportBody},
        TContext
      > => {

      const mutationOptions = getStartImportApiV1ImportsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Import Runs
 */
export const listImportRunsApiV1ImportsGet = (
    params?: ListImportRunsApiV1ImportsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseImportRunResponse>(
      {url: `/api/v1/imports`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListImportRunsApiV1ImportsGetQueryKey = (params?: ListImportRunsApiV1ImportsGetParams,) => {
    return [
    `/api/v1/imports`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListImportRunsApiV1ImportsGetQueryOptions = <TData = Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError = HTTPValidationError>(params?: ListImportRunsApiV1ImportsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListImportRunsApiV1ImportsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>> = ({ signal }) => listImportRunsApiV1ImportsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListImportRunsApiV1ImportsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>>
export type ListImportRunsApiV1ImportsGetQueryError = HTTPValidationError


export function useListImportRunsApiV1ImportsGet<TData = Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListImportRunsApiV1ImportsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>,
          TError,
          Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListImportRunsApiV1ImportsGet<TData = Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError = HTTPValidationError>(
 params?: ListImportRunsApiV1ImportsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>,
          TError,
          Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListImportRunsApiV1ImportsGet<TData = Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError = HTTPValidationError>(
 params?: ListImportRunsApiV1ImportsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Import Runs
 */

export function useListImportRunsApiV1ImportsGet<TData = Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError = HTTPValidationError>(
 params?: ListImportRunsApiV1ImportsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listImportRunsApiV1ImportsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListImportRunsApiV1ImportsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Import Run
 */
export const getImportRunApiV1ImportsImportRunIdGet = (
    importRunId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ImportRunResponse>(
      {url: `/api/v1/imports/${importRunId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetImportRunApiV1ImportsImportRunIdGetQueryKey = (importRunId?: string,) => {
    return [
    `/api/v1/imports/${importRunId}`
    ] as const;
    }

    
export const getGetImportRunApiV1ImportsImportRunIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError = HTTPValidationError>(importRunId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetImportRunApiV1ImportsImportRunIdGetQueryKey(importRunId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>> = ({ signal }) => getImportRunApiV1ImportsImportRunIdGet(importRunId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(importRunId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetImportRunApiV1ImportsImportRunIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>>
export type GetImportRunApiV1ImportsImportRunIdGetQueryError = HTTPValidationError


export function useGetImportRunApiV1ImportsImportRunIdGet<TData = Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError = HTTPValidationError>(
 importRunId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImportRunApiV1ImportsImportRunIdGet<TData = Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError = HTTPValidationError>(
 importRunId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>,
          TError,
          Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImportRunApiV1ImportsImportRunIdGet<TData = Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError = HTTPValidationError>(
 importRunId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Import Run
 */

export function useGetImportRunApiV1ImportsImportRunIdGet<TData = Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError = HTTPValidationError>(
 importRunId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportRunApiV1ImportsImportRunIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetImportRunApiV1ImportsImportRunIdGetQueryOptions(importRunId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Store a raw upload for an import adapter to parse later.

``import_type=target_biology`` stores the file's bytes unchanged —
``parse_workbook`` needs a real multi-sheet XLSX, not the two-column
``locus\tcall`` TSV every other caller of this route gets. Omitting
``import_type`` (every other caller today) keeps the original behaviour:
convert to that TSV, which is what the DeJesus essentiality plugin expects.
 * @summary Upload Essentiality File
 */
export const uploadEssentialityFileApiV1ImportsUploadsPost = (
    bodyUploadEssentialityFileApiV1ImportsUploadsPost: BodyUploadEssentialityFileApiV1ImportsUploadsPost,
    params?: UploadEssentialityFileApiV1ImportsUploadsPostParams,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadEssentialityFileApiV1ImportsUploadsPost.file)

      return customInstance<UploadResponse>(
      {url: `/api/v1/imports/uploads`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params, signal
    },
      );
    }
  


export const getUploadEssentialityFileApiV1ImportsUploadsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>, TError,{data: BodyUploadEssentialityFileApiV1ImportsUploadsPost;params?: UploadEssentialityFileApiV1ImportsUploadsPostParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>, TError,{data: BodyUploadEssentialityFileApiV1ImportsUploadsPost;params?: UploadEssentialityFileApiV1ImportsUploadsPostParams}, TContext> => {

const mutationKey = ['uploadEssentialityFileApiV1ImportsUploadsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>, {data: BodyUploadEssentialityFileApiV1ImportsUploadsPost;params?: UploadEssentialityFileApiV1ImportsUploadsPostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadEssentialityFileApiV1ImportsUploadsPost(data,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadEssentialityFileApiV1ImportsUploadsPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>>
    export type UploadEssentialityFileApiV1ImportsUploadsPostMutationBody = BodyUploadEssentialityFileApiV1ImportsUploadsPost
    export type UploadEssentialityFileApiV1ImportsUploadsPostMutationError = HTTPValidationError

    /**
 * @summary Upload Essentiality File
 */
export const useUploadEssentialityFileApiV1ImportsUploadsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>, TError,{data: BodyUploadEssentialityFileApiV1ImportsUploadsPost;params?: UploadEssentialityFileApiV1ImportsUploadsPostParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadEssentialityFileApiV1ImportsUploadsPost>>,
        TError,
        {data: BodyUploadEssentialityFileApiV1ImportsUploadsPost;params?: UploadEssentialityFileApiV1ImportsUploadsPostParams},
        TContext
      > => {

      const mutationOptions = getUploadEssentialityFileApiV1ImportsUploadsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    