/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTargetBody,
  HTTPValidationError,
  ListTargetsApiV1TargetsGetParams,
  PaginatedResponseTargetResponse,
  TargetResponse,
  UpdateTargetBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Targets
 */
export const listTargetsApiV1TargetsGet = (
    params?: ListTargetsApiV1TargetsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseTargetResponse>(
      {url: `/api/v1/targets`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListTargetsApiV1TargetsGetQueryKey = (params?: ListTargetsApiV1TargetsGetParams,) => {
    return [
    `/api/v1/targets`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTargetsApiV1TargetsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError = HTTPValidationError>(params?: ListTargetsApiV1TargetsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTargetsApiV1TargetsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>> = ({ signal }) => listTargetsApiV1TargetsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTargetsApiV1TargetsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>>
export type ListTargetsApiV1TargetsGetQueryError = HTTPValidationError


export function useListTargetsApiV1TargetsGet<TData = Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTargetsApiV1TargetsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>,
          TError,
          Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTargetsApiV1TargetsGet<TData = Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError = HTTPValidationError>(
 params?: ListTargetsApiV1TargetsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>,
          TError,
          Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTargetsApiV1TargetsGet<TData = Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError = HTTPValidationError>(
 params?: ListTargetsApiV1TargetsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Targets
 */

export function useListTargetsApiV1TargetsGet<TData = Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError = HTTPValidationError>(
 params?: ListTargetsApiV1TargetsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTargetsApiV1TargetsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTargetsApiV1TargetsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Target
 */
export const createTargetApiV1TargetsPost = (
    createTargetBody: CreateTargetBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TargetResponse>(
      {url: `/api/v1/targets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTargetBody, signal
    },
      );
    }
  


export const getCreateTargetApiV1TargetsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>, TError,{data: CreateTargetBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>, TError,{data: CreateTargetBody}, TContext> => {

const mutationKey = ['createTargetApiV1TargetsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>, {data: CreateTargetBody}> = (props) => {
          const {data} = props ?? {};

          return  createTargetApiV1TargetsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTargetApiV1TargetsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>>
    export type CreateTargetApiV1TargetsPostMutationBody = CreateTargetBody
    export type CreateTargetApiV1TargetsPostMutationError = HTTPValidationError

    /**
 * @summary Create Target
 */
export const useCreateTargetApiV1TargetsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>, TError,{data: CreateTargetBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTargetApiV1TargetsPost>>,
        TError,
        {data: CreateTargetBody},
        TContext
      > => {

      const mutationOptions = getCreateTargetApiV1TargetsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Target
 */
export const getTargetApiV1TargetsTargetIdGet = (
    targetId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TargetResponse>(
      {url: `/api/v1/targets/${targetId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTargetApiV1TargetsTargetIdGetQueryKey = (targetId?: string,) => {
    return [
    `/api/v1/targets/${targetId}`
    ] as const;
    }

    
export const getGetTargetApiV1TargetsTargetIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError = HTTPValidationError>(targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTargetApiV1TargetsTargetIdGetQueryKey(targetId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>> = ({ signal }) => getTargetApiV1TargetsTargetIdGet(targetId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(targetId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTargetApiV1TargetsTargetIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>>
export type GetTargetApiV1TargetsTargetIdGetQueryError = HTTPValidationError


export function useGetTargetApiV1TargetsTargetIdGet<TData = Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError = HTTPValidationError>(
 targetId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetApiV1TargetsTargetIdGet<TData = Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError = HTTPValidationError>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetApiV1TargetsTargetIdGet<TData = Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError = HTTPValidationError>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Target
 */

export function useGetTargetApiV1TargetsTargetIdGet<TData = Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError = HTTPValidationError>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetApiV1TargetsTargetIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTargetApiV1TargetsTargetIdGetQueryOptions(targetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Target
 */
export const updateTargetApiV1TargetsTargetIdPatch = (
    targetId: string,
    updateTargetBody: UpdateTargetBody,
 ) => {
      
      
      return customInstance<TargetResponse>(
      {url: `/api/v1/targets/${targetId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTargetBody
    },
      );
    }
  


export const getUpdateTargetApiV1TargetsTargetIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>, TError,{targetId: string;data: UpdateTargetBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>, TError,{targetId: string;data: UpdateTargetBody}, TContext> => {

const mutationKey = ['updateTargetApiV1TargetsTargetIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>, {targetId: string;data: UpdateTargetBody}> = (props) => {
          const {targetId,data} = props ?? {};

          return  updateTargetApiV1TargetsTargetIdPatch(targetId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTargetApiV1TargetsTargetIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>>
    export type UpdateTargetApiV1TargetsTargetIdPatchMutationBody = UpdateTargetBody
    export type UpdateTargetApiV1TargetsTargetIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Target
 */
export const useUpdateTargetApiV1TargetsTargetIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>, TError,{targetId: string;data: UpdateTargetBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTargetApiV1TargetsTargetIdPatch>>,
        TError,
        {targetId: string;data: UpdateTargetBody},
        TContext
      > => {

      const mutationOptions = getUpdateTargetApiV1TargetsTargetIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    