/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ImportRunResponse,
  PluginManifestResponse,
  StartPluginRunBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Plugins
 */
export const listPluginsApiV1PluginsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PluginManifestResponse[]>(
      {url: `/api/v1/plugins`, method: 'GET', signal
    },
      );
    }
  



export const getListPluginsApiV1PluginsGetQueryKey = () => {
    return [
    `/api/v1/plugins`
    ] as const;
    }

    
export const getListPluginsApiV1PluginsGetQueryOptions = <TData = Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPluginsApiV1PluginsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>> = ({ signal }) => listPluginsApiV1PluginsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPluginsApiV1PluginsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>>
export type ListPluginsApiV1PluginsGetQueryError = unknown


export function useListPluginsApiV1PluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>,
          TError,
          Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPluginsApiV1PluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>,
          TError,
          Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPluginsApiV1PluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Plugins
 */

export function useListPluginsApiV1PluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiV1PluginsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPluginsApiV1PluginsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Start Plugin Run
 */
export const startPluginRunApiV1PluginsPluginIdRunsPost = (
    pluginId: string,
    startPluginRunBody: StartPluginRunBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ImportRunResponse>(
      {url: `/api/v1/plugins/${pluginId}/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startPluginRunBody, signal
    },
      );
    }
  


export const getStartPluginRunApiV1PluginsPluginIdRunsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>, TError,{pluginId: string;data: StartPluginRunBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>, TError,{pluginId: string;data: StartPluginRunBody}, TContext> => {

const mutationKey = ['startPluginRunApiV1PluginsPluginIdRunsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>, {pluginId: string;data: StartPluginRunBody}> = (props) => {
          const {pluginId,data} = props ?? {};

          return  startPluginRunApiV1PluginsPluginIdRunsPost(pluginId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartPluginRunApiV1PluginsPluginIdRunsPostMutationResult = NonNullable<Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>>
    export type StartPluginRunApiV1PluginsPluginIdRunsPostMutationBody = StartPluginRunBody
    export type StartPluginRunApiV1PluginsPluginIdRunsPostMutationError = HTTPValidationError

    /**
 * @summary Start Plugin Run
 */
export const useStartPluginRunApiV1PluginsPluginIdRunsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>, TError,{pluginId: string;data: StartPluginRunBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startPluginRunApiV1PluginsPluginIdRunsPost>>,
        TError,
        {pluginId: string;data: StartPluginRunBody},
        TContext
      > => {

      const mutationOptions = getStartPluginRunApiV1PluginsPluginIdRunsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    