/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * prot-cellar
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateStrainBody,
  HTTPValidationError,
  ListStrainsApiV1StrainsGetParams,
  PaginatedResponseStrainResponse,
  StrainResponse,
  UpdateStrainBody
} from '.././model';

import { customInstance } from '.././custom-instance';




/**
 * @summary List Strains
 */
export const listStrainsApiV1StrainsGet = (
    params?: ListStrainsApiV1StrainsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseStrainResponse>(
      {url: `/api/v1/strains`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListStrainsApiV1StrainsGetQueryKey = (params?: ListStrainsApiV1StrainsGetParams,) => {
    return [
    `/api/v1/strains`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListStrainsApiV1StrainsGetQueryOptions = <TData = Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError = HTTPValidationError>(params?: ListStrainsApiV1StrainsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStrainsApiV1StrainsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>> = ({ signal }) => listStrainsApiV1StrainsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStrainsApiV1StrainsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>>
export type ListStrainsApiV1StrainsGetQueryError = HTTPValidationError


export function useListStrainsApiV1StrainsGet<TData = Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListStrainsApiV1StrainsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>,
          TError,
          Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStrainsApiV1StrainsGet<TData = Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError = HTTPValidationError>(
 params?: ListStrainsApiV1StrainsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>,
          TError,
          Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStrainsApiV1StrainsGet<TData = Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError = HTTPValidationError>(
 params?: ListStrainsApiV1StrainsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Strains
 */

export function useListStrainsApiV1StrainsGet<TData = Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError = HTTPValidationError>(
 params?: ListStrainsApiV1StrainsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStrainsApiV1StrainsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStrainsApiV1StrainsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Strain
 */
export const createStrainApiV1StrainsPost = (
    createStrainBody: CreateStrainBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<StrainResponse>(
      {url: `/api/v1/strains`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStrainBody, signal
    },
      );
    }
  


export const getCreateStrainApiV1StrainsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>, TError,{data: CreateStrainBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>, TError,{data: CreateStrainBody}, TContext> => {

const mutationKey = ['createStrainApiV1StrainsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>, {data: CreateStrainBody}> = (props) => {
          const {data} = props ?? {};

          return  createStrainApiV1StrainsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStrainApiV1StrainsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>>
    export type CreateStrainApiV1StrainsPostMutationBody = CreateStrainBody
    export type CreateStrainApiV1StrainsPostMutationError = HTTPValidationError

    /**
 * @summary Create Strain
 */
export const useCreateStrainApiV1StrainsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>, TError,{data: CreateStrainBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStrainApiV1StrainsPost>>,
        TError,
        {data: CreateStrainBody},
        TContext
      > => {

      const mutationOptions = getCreateStrainApiV1StrainsPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Strain
 */
export const getStrainApiV1StrainsStrainIdGet = (
    strainId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<StrainResponse>(
      {url: `/api/v1/strains/${strainId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetStrainApiV1StrainsStrainIdGetQueryKey = (strainId?: string,) => {
    return [
    `/api/v1/strains/${strainId}`
    ] as const;
    }

    
export const getGetStrainApiV1StrainsStrainIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError = HTTPValidationError>(strainId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStrainApiV1StrainsStrainIdGetQueryKey(strainId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>> = ({ signal }) => getStrainApiV1StrainsStrainIdGet(strainId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(strainId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStrainApiV1StrainsStrainIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>>
export type GetStrainApiV1StrainsStrainIdGetQueryError = HTTPValidationError


export function useGetStrainApiV1StrainsStrainIdGet<TData = Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError = HTTPValidationError>(
 strainId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStrainApiV1StrainsStrainIdGet<TData = Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError = HTTPValidationError>(
 strainId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStrainApiV1StrainsStrainIdGet<TData = Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError = HTTPValidationError>(
 strainId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Strain
 */

export function useGetStrainApiV1StrainsStrainIdGet<TData = Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError = HTTPValidationError>(
 strainId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStrainApiV1StrainsStrainIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStrainApiV1StrainsStrainIdGetQueryOptions(strainId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Strain
 */
export const updateStrainApiV1StrainsStrainIdPatch = (
    strainId: string,
    updateStrainBody: UpdateStrainBody,
 ) => {
      
      
      return customInstance<StrainResponse>(
      {url: `/api/v1/strains/${strainId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateStrainBody
    },
      );
    }
  


export const getUpdateStrainApiV1StrainsStrainIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>, TError,{strainId: string;data: UpdateStrainBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>, TError,{strainId: string;data: UpdateStrainBody}, TContext> => {

const mutationKey = ['updateStrainApiV1StrainsStrainIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>, {strainId: string;data: UpdateStrainBody}> = (props) => {
          const {strainId,data} = props ?? {};

          return  updateStrainApiV1StrainsStrainIdPatch(strainId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStrainApiV1StrainsStrainIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>>
    export type UpdateStrainApiV1StrainsStrainIdPatchMutationBody = UpdateStrainBody
    export type UpdateStrainApiV1StrainsStrainIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Strain
 */
export const useUpdateStrainApiV1StrainsStrainIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>, TError,{strainId: string;data: UpdateStrainBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStrainApiV1StrainsStrainIdPatch>>,
        TError,
        {strainId: string;data: UpdateStrainBody},
        TContext
      > => {

      const mutationOptions = getUpdateStrainApiV1StrainsStrainIdPatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    